/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/AWTForms/Dialog.java to edit this template
 */
package rekammedis;

/**
 *
 * @author USER
 */
public class DlgBerkasDigitalPerawatan extends java.awt.Dialog {

    /**
     * Creates new form DlgBerkasDigitalPerawatan
     */
    public DlgBerkasDigitalPerawatan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelHeader = new javax.swing.JPanel();
        panelShortcut = new javax.swing.JPanel();
        scrollPreview = new javax.swing.JScrollPane();
        lblPreview = new javax.swing.JLabel();
        panelBottom = new javax.swing.JPanel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        add(panelHeader, java.awt.BorderLayout.CENTER);
        add(panelShortcut, java.awt.BorderLayout.NORTH);

        lblPreview.setText("jLabel1");
        scrollPreview.setViewportView(lblPreview);

        add(scrollPreview, java.awt.BorderLayout.SOUTH);
        add(panelBottom, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btnChooseFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFileActionPerformed

    }//GEN-LAST:event_btnChooseFileActionPerformed

    private void btnChooseFileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnChooseFileKeyPressed
 
    }//GEN-LAST:event_btnChooseFileKeyPressed

    private void btnKosongkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongkanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKosongkanActionPerformed

    private void btnKosongkanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnKosongkanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKosongkanKeyPressed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnSimpanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSimpanKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanKeyPressed

    private void btnHapusJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusJenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusJenisActionPerformed

    private void btnHapusJenisKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnHapusJenisKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusJenisKeyPressed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnKeluarKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKeluarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DlgBerkasDigitalPerawatan dialog = new DlgBerkasDigitalPerawatan(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPreview;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelHeader;
    private javax.swing.JPanel panelShortcut;
    private javax.swing.JScrollPane scrollPreview;
    // End of variables declaration//GEN-END:variables
}
