/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgKtgPenyakit.java
 *
 * Created on May 23, 2010, 12:15:01 AM
 */

package laporan;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;


/**
 *
 * @author dosen
 */
public final class CeklisPelayananRehabMedik extends javax.swing.JDialog {
    
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private PreparedStatement ps;
    private ResultSet rs;
    private int i;
    private final ButtonGroup bgSiTB = new ButtonGroup();    

    /** Creates new form DlgKtgPenyakit
     * @param parent
     * @param modal */
    public CeklisPelayananRehabMedik(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();      
        
        // Initial placement/size (adjust as needed)
        this.setLocation(10, 5);
        this.setSize(1100, 750);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TNoRwCari = new widget.TextBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        internalFrame1 = new widget.InternalFrame();
        panelGlass8 = new widget.panelisi();
        jLabel27 = new widget.Label();
        BtnSimpanTB = new widget.Button();
        jLabel28 = new widget.Label();
        BtnKeluar = new widget.Button();
        panelGlass2 = new widget.panelisi();
        jPanel1 = new javax.swing.JPanel();
        jLabel22 = new widget.Label();
        LabelMedis = new widget.Label();
        CBGaitAnalyzer = new javax.swing.JCheckBox();
        LblIdentitas = new widget.Label();
        jSeparator1 = new javax.swing.JSeparator();
        CBEmg = new javax.swing.JCheckBox();
        CBUroDinamic = new javax.swing.JCheckBox();
        CBSideBack = new javax.swing.JCheckBox();
        CBENTree = new javax.swing.JCheckBox();
        CBSpyrometer = new javax.swing.JCheckBox();
        CBStaticBicycle = new javax.swing.JCheckBox();
        CBTreadMill = new javax.swing.JCheckBox();
        CBBodyPlatysmograf = new javax.swing.JCheckBox();
        LabelFisioterapi = new widget.Label();
        CBLatihanFisik = new javax.swing.JCheckBox();
        CBAktinoterapi = new javax.swing.JCheckBox();
        CBElektroterapi = new javax.swing.JCheckBox();
        CBHidroterapi = new javax.swing.JCheckBox();
        CBTraksiLumbal = new javax.swing.JCheckBox();
        CBFisioterapiAnak = new javax.swing.JCheckBox();
        LabelOkupasiterapi = new widget.Label();
        CBSnoosienRoom = new javax.swing.JCheckBox();
        CBSensoriIntegrasi = new javax.swing.JCheckBox();
        CBLatihanAktivitasKehidupan = new javax.swing.JCheckBox();
        CBProperBodyMekanik = new javax.swing.JCheckBox();
        CBPembuatanAlatLontar = new javax.swing.JCheckBox();
        CBAnalisaPersiapanKerja = new javax.swing.JCheckBox();
        CBLatihanRelaksasi = new javax.swing.JCheckBox();
        CBAnalisadanIntervensi = new javax.swing.JCheckBox();
        CBOkupasiterapiAnak = new javax.swing.JCheckBox();
        LabelTerapiWicara = new widget.Label();
        CBFungsiBicara = new javax.swing.JCheckBox();
        CBFungsiBahasa = new javax.swing.JCheckBox();
        CBFungsiMenelan = new javax.swing.JCheckBox();
        CBTerapiWicaraAnak = new javax.swing.JCheckBox();
        LabelPsikologi = new widget.Label();
        CBPsikologiAnak = new javax.swing.JCheckBox();
        CBPsikologiDewasa = new javax.swing.JCheckBox();
        LabelSosialMedik = new widget.Label();
        CBEvaluasiLingkungan = new javax.swing.JCheckBox();
        CBEvaluasiEkonomi = new javax.swing.JCheckBox();
        CBEvaluasiPekerjaan = new javax.swing.JCheckBox();
        LabelOrtotikProstetik = new widget.Label();
        CBPembuatanAlatBantu = new javax.swing.JCheckBox();
        CBPembuatanAlatAnggotaTiruan = new javax.swing.JCheckBox();
        BtnLihatRekap = new widget.Button();

        TNoRwCari.setHighlighter(null);
        TNoRwCari.setName("TNoRwCari"); // NOI18N
        TNoRwCari.setPreferredSize(new java.awt.Dimension(120, 23));
        TNoRwCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TNoRwCariMouseClicked(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Verifikasi Pasien TB");
        setModal(true);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setPreferredSize(new java.awt.Dimension(1100, 750));
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass8.setBackground(new java.awt.Color(204, 204, 204));
        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(44, 60));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N
        jLabel27.setPreferredSize(new java.awt.Dimension(15, 0));
        panelGlass8.add(jLabel27);

        BtnSimpanTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpanTB.setMnemonic('S');
        BtnSimpanTB.setText("Simpan");
        BtnSimpanTB.setToolTipText("Alt+S");
        BtnSimpanTB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnSimpanTB.setIconTextGap(10);
        BtnSimpanTB.setName("BtnSimpanTB"); // NOI18N
        BtnSimpanTB.setPreferredSize(new java.awt.Dimension(85, 30));
        BtnSimpanTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanTBActionPerformed(evt);
            }
        });
        panelGlass8.add(BtnSimpanTB);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setName("jLabel28"); // NOI18N
        jLabel28.setPreferredSize(new java.awt.Dimension(210, 0));
        panelGlass8.add(jLabel28);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(85, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        internalFrame1.add(panelGlass8, java.awt.BorderLayout.SOUTH);

        panelGlass2.setName("panelGlass2"); // NOI18N
        panelGlass2.setPreferredSize(new java.awt.Dimension(1100, 750));
        panelGlass2.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setName("jPanel1"); // NOI18N
        panelGlass2.add(jPanel1);
        jPanel1.setBounds(0, 0, 1100, 60);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Checklis Kegiatan Pelayanan Rehabilitasi Medik ");
        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N
        panelGlass2.add(jLabel22);
        jLabel22.setBounds(30, 20, 590, 30);

        LabelMedis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelMedis.setText("Medis");
        LabelMedis.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        LabelMedis.setName("LabelMedis"); // NOI18N
        panelGlass2.add(LabelMedis);
        LabelMedis.setBounds(30, 130, 100, 23);

        CBGaitAnalyzer.setBackground(new java.awt.Color(255, 255, 255));
        CBGaitAnalyzer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBGaitAnalyzer.setText("Gait Analyzer");
        CBGaitAnalyzer.setIconTextGap(10);
        CBGaitAnalyzer.setName("CBGaitAnalyzer"); // NOI18N
        CBGaitAnalyzer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBGaitAnalyzerActionPerformed(evt);
            }
        });
        panelGlass2.add(CBGaitAnalyzer);
        CBGaitAnalyzer.setBounds(30, 160, 140, 29);

        LblIdentitas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblIdentitas.setText("123456   Mustafa Daeng Muma");
        LblIdentitas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LblIdentitas.setName("LblIdentitas"); // NOI18N
        panelGlass2.add(LblIdentitas);
        LblIdentitas.setBounds(30, 80, 780, 23);
        LblIdentitas.getAccessibleContext().setAccessibleName("");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setName("jSeparator1"); // NOI18N
        panelGlass2.add(jSeparator1);
        jSeparator1.setBounds(30, 110, 600, 2);

        CBEmg.setBackground(new java.awt.Color(255, 255, 255));
        CBEmg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBEmg.setText("E M G");
        CBEmg.setIconTextGap(10);
        CBEmg.setName("CBEmg"); // NOI18N
        CBEmg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBEmgActionPerformed(evt);
            }
        });
        panelGlass2.add(CBEmg);
        CBEmg.setBounds(30, 190, 90, 29);

        CBUroDinamic.setBackground(new java.awt.Color(255, 255, 255));
        CBUroDinamic.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBUroDinamic.setText("Uro Dinamic");
        CBUroDinamic.setIconTextGap(10);
        CBUroDinamic.setName("CBUroDinamic"); // NOI18N
        CBUroDinamic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBUroDinamicActionPerformed(evt);
            }
        });
        panelGlass2.add(CBUroDinamic);
        CBUroDinamic.setBounds(30, 220, 130, 29);

        CBSideBack.setBackground(new java.awt.Color(255, 255, 255));
        CBSideBack.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBSideBack.setText("Side Back");
        CBSideBack.setIconTextGap(10);
        CBSideBack.setName("CBSideBack"); // NOI18N
        CBSideBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBSideBackActionPerformed(evt);
            }
        });
        panelGlass2.add(CBSideBack);
        CBSideBack.setBounds(30, 250, 110, 29);

        CBENTree.setBackground(new java.awt.Color(255, 255, 255));
        CBENTree.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBENTree.setText("EN Tree");
        CBENTree.setIconTextGap(10);
        CBENTree.setName("CBENTree"); // NOI18N
        CBENTree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBENTreeActionPerformed(evt);
            }
        });
        panelGlass2.add(CBENTree);
        CBENTree.setBounds(30, 280, 100, 29);

        CBSpyrometer.setBackground(new java.awt.Color(255, 255, 255));
        CBSpyrometer.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBSpyrometer.setText("Spyrometer");
        CBSpyrometer.setIconTextGap(10);
        CBSpyrometer.setName("CBSpyrometer"); // NOI18N
        CBSpyrometer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBSpyrometerActionPerformed(evt);
            }
        });
        panelGlass2.add(CBSpyrometer);
        CBSpyrometer.setBounds(30, 310, 120, 29);

        CBStaticBicycle.setBackground(new java.awt.Color(255, 255, 255));
        CBStaticBicycle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBStaticBicycle.setText("Static Bicycle");
        CBStaticBicycle.setIconTextGap(10);
        CBStaticBicycle.setName("CBStaticBicycle"); // NOI18N
        CBStaticBicycle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBStaticBicycleActionPerformed(evt);
            }
        });
        panelGlass2.add(CBStaticBicycle);
        CBStaticBicycle.setBounds(30, 340, 130, 29);

        CBTreadMill.setBackground(new java.awt.Color(255, 255, 255));
        CBTreadMill.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBTreadMill.setText("Tread Mill");
        CBTreadMill.setIconTextGap(10);
        CBTreadMill.setName("CBTreadMill"); // NOI18N
        CBTreadMill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTreadMillActionPerformed(evt);
            }
        });
        panelGlass2.add(CBTreadMill);
        CBTreadMill.setBounds(30, 370, 120, 29);

        CBBodyPlatysmograf.setBackground(new java.awt.Color(255, 255, 255));
        CBBodyPlatysmograf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBBodyPlatysmograf.setText("Body Platysmograf");
        CBBodyPlatysmograf.setIconTextGap(10);
        CBBodyPlatysmograf.setName("CBBodyPlatysmograf"); // NOI18N
        CBBodyPlatysmograf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBBodyPlatysmografActionPerformed(evt);
            }
        });
        panelGlass2.add(CBBodyPlatysmograf);
        CBBodyPlatysmograf.setBounds(30, 400, 170, 29);

        LabelFisioterapi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelFisioterapi.setText("Fisioterapi");
        LabelFisioterapi.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        LabelFisioterapi.setName("LabelFisioterapi"); // NOI18N
        panelGlass2.add(LabelFisioterapi);
        LabelFisioterapi.setBounds(270, 130, 140, 23);

        CBLatihanFisik.setBackground(new java.awt.Color(255, 255, 255));
        CBLatihanFisik.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBLatihanFisik.setText("Latihan Fisik");
        CBLatihanFisik.setIconTextGap(10);
        CBLatihanFisik.setName("CBLatihanFisik"); // NOI18N
        CBLatihanFisik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBLatihanFisikActionPerformed(evt);
            }
        });
        panelGlass2.add(CBLatihanFisik);
        CBLatihanFisik.setBounds(270, 160, 140, 29);

        CBAktinoterapi.setBackground(new java.awt.Color(255, 255, 255));
        CBAktinoterapi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBAktinoterapi.setText("Aktinoterapi");
        CBAktinoterapi.setIconTextGap(10);
        CBAktinoterapi.setName("CBAktinoterapi"); // NOI18N
        CBAktinoterapi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBAktinoterapiActionPerformed(evt);
            }
        });
        panelGlass2.add(CBAktinoterapi);
        CBAktinoterapi.setBounds(270, 190, 130, 29);

        CBElektroterapi.setBackground(new java.awt.Color(255, 255, 255));
        CBElektroterapi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBElektroterapi.setText("Elektroterapi");
        CBElektroterapi.setIconTextGap(10);
        CBElektroterapi.setName("CBElektroterapi"); // NOI18N
        CBElektroterapi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBElektroterapiActionPerformed(evt);
            }
        });
        panelGlass2.add(CBElektroterapi);
        CBElektroterapi.setBounds(270, 220, 140, 29);

        CBHidroterapi.setBackground(new java.awt.Color(255, 255, 255));
        CBHidroterapi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBHidroterapi.setText("Hidroterapi");
        CBHidroterapi.setIconTextGap(10);
        CBHidroterapi.setName("CBHidroterapi"); // NOI18N
        CBHidroterapi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBHidroterapiActionPerformed(evt);
            }
        });
        panelGlass2.add(CBHidroterapi);
        CBHidroterapi.setBounds(270, 250, 130, 29);

        CBTraksiLumbal.setBackground(new java.awt.Color(255, 255, 255));
        CBTraksiLumbal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBTraksiLumbal.setText("Traksi Lumbal dan Cervical");
        CBTraksiLumbal.setIconTextGap(10);
        CBTraksiLumbal.setName("CBTraksiLumbal"); // NOI18N
        CBTraksiLumbal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTraksiLumbalActionPerformed(evt);
            }
        });
        panelGlass2.add(CBTraksiLumbal);
        CBTraksiLumbal.setBounds(270, 280, 220, 29);

        CBFisioterapiAnak.setBackground(new java.awt.Color(255, 255, 255));
        CBFisioterapiAnak.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBFisioterapiAnak.setText("Fisioterapi Anak");
        CBFisioterapiAnak.setIconTextGap(10);
        CBFisioterapiAnak.setName("CBFisioterapiAnak"); // NOI18N
        CBFisioterapiAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBFisioterapiAnakActionPerformed(evt);
            }
        });
        panelGlass2.add(CBFisioterapiAnak);
        CBFisioterapiAnak.setBounds(270, 310, 150, 29);

        LabelOkupasiterapi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelOkupasiterapi.setText("Okupasiterapi");
        LabelOkupasiterapi.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        LabelOkupasiterapi.setName("LabelOkupasiterapi"); // NOI18N
        panelGlass2.add(LabelOkupasiterapi);
        LabelOkupasiterapi.setBounds(530, 130, 160, 23);

        CBSnoosienRoom.setBackground(new java.awt.Color(255, 255, 255));
        CBSnoosienRoom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBSnoosienRoom.setText("Snoosien Room");
        CBSnoosienRoom.setIconTextGap(10);
        CBSnoosienRoom.setName("CBSnoosienRoom"); // NOI18N
        CBSnoosienRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBSnoosienRoomActionPerformed(evt);
            }
        });
        panelGlass2.add(CBSnoosienRoom);
        CBSnoosienRoom.setBounds(530, 160, 200, 29);

        CBSensoriIntegrasi.setBackground(new java.awt.Color(255, 255, 255));
        CBSensoriIntegrasi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBSensoriIntegrasi.setText("Sensori Integrasi");
        CBSensoriIntegrasi.setIconTextGap(10);
        CBSensoriIntegrasi.setName("CBSensoriIntegrasi"); // NOI18N
        CBSensoriIntegrasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBSensoriIntegrasiActionPerformed(evt);
            }
        });
        panelGlass2.add(CBSensoriIntegrasi);
        CBSensoriIntegrasi.setBounds(530, 190, 150, 29);

        CBLatihanAktivitasKehidupan.setBackground(new java.awt.Color(255, 255, 255));
        CBLatihanAktivitasKehidupan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBLatihanAktivitasKehidupan.setText("Latihan Aktivitas Kehidupan Sehari-hari");
        CBLatihanAktivitasKehidupan.setIconTextGap(10);
        CBLatihanAktivitasKehidupan.setName("CBLatihanAktivitasKehidupan"); // NOI18N
        CBLatihanAktivitasKehidupan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBLatihanAktivitasKehidupanActionPerformed(evt);
            }
        });
        panelGlass2.add(CBLatihanAktivitasKehidupan);
        CBLatihanAktivitasKehidupan.setBounds(530, 220, 300, 29);

        CBProperBodyMekanik.setBackground(new java.awt.Color(255, 255, 255));
        CBProperBodyMekanik.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBProperBodyMekanik.setText("Proper Body Mekanik");
        CBProperBodyMekanik.setIconTextGap(10);
        CBProperBodyMekanik.setName("CBProperBodyMekanik"); // NOI18N
        CBProperBodyMekanik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBProperBodyMekanikActionPerformed(evt);
            }
        });
        panelGlass2.add(CBProperBodyMekanik);
        CBProperBodyMekanik.setBounds(530, 250, 180, 29);

        CBPembuatanAlatLontar.setBackground(new java.awt.Color(255, 255, 255));
        CBPembuatanAlatLontar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBPembuatanAlatLontar.setText("Pembuatan Alat Lontar dan Adaptasi Alat ");
        CBPembuatanAlatLontar.setIconTextGap(10);
        CBPembuatanAlatLontar.setName("CBPembuatanAlatLontar"); // NOI18N
        CBPembuatanAlatLontar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPembuatanAlatLontarActionPerformed(evt);
            }
        });
        panelGlass2.add(CBPembuatanAlatLontar);
        CBPembuatanAlatLontar.setBounds(530, 280, 310, 29);

        CBAnalisaPersiapanKerja.setBackground(new java.awt.Color(255, 255, 255));
        CBAnalisaPersiapanKerja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBAnalisaPersiapanKerja.setText("Analisa Persiapan Kerja");
        CBAnalisaPersiapanKerja.setIconTextGap(10);
        CBAnalisaPersiapanKerja.setName("CBAnalisaPersiapanKerja"); // NOI18N
        CBAnalisaPersiapanKerja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBAnalisaPersiapanKerjaActionPerformed(evt);
            }
        });
        panelGlass2.add(CBAnalisaPersiapanKerja);
        CBAnalisaPersiapanKerja.setBounds(530, 310, 180, 29);

        CBLatihanRelaksasi.setBackground(new java.awt.Color(255, 255, 255));
        CBLatihanRelaksasi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBLatihanRelaksasi.setText("Latihan Relaksasi");
        CBLatihanRelaksasi.setIconTextGap(10);
        CBLatihanRelaksasi.setName("CBLatihanRelaksasi"); // NOI18N
        CBLatihanRelaksasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBLatihanRelaksasiActionPerformed(evt);
            }
        });
        panelGlass2.add(CBLatihanRelaksasi);
        CBLatihanRelaksasi.setBounds(530, 340, 160, 29);

        CBAnalisadanIntervensi.setBackground(new java.awt.Color(255, 255, 255));
        CBAnalisadanIntervensi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBAnalisadanIntervensi.setText("Analisa dan Intervensi, Persepsi, Kognitif, Psikomotorik ");
        CBAnalisadanIntervensi.setIconTextGap(10);
        CBAnalisadanIntervensi.setName("CBAnalisadanIntervensi"); // NOI18N
        CBAnalisadanIntervensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBAnalisadanIntervensiActionPerformed(evt);
            }
        });
        panelGlass2.add(CBAnalisadanIntervensi);
        CBAnalisadanIntervensi.setBounds(530, 370, 390, 29);

        CBOkupasiterapiAnak.setBackground(new java.awt.Color(255, 255, 255));
        CBOkupasiterapiAnak.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBOkupasiterapiAnak.setText("Okupasiterapi Anak");
        CBOkupasiterapiAnak.setIconTextGap(10);
        CBOkupasiterapiAnak.setName("CBOkupasiterapiAnak"); // NOI18N
        CBOkupasiterapiAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOkupasiterapiAnakActionPerformed(evt);
            }
        });
        panelGlass2.add(CBOkupasiterapiAnak);
        CBOkupasiterapiAnak.setBounds(530, 400, 180, 29);

        LabelTerapiWicara.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelTerapiWicara.setText("Terapi Wicara");
        LabelTerapiWicara.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        LabelTerapiWicara.setName("LabelTerapiWicara"); // NOI18N
        panelGlass2.add(LabelTerapiWicara);
        LabelTerapiWicara.setBounds(270, 350, 200, 23);

        CBFungsiBicara.setBackground(new java.awt.Color(255, 255, 255));
        CBFungsiBicara.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBFungsiBicara.setText("Fungsi Bicara");
        CBFungsiBicara.setIconTextGap(10);
        CBFungsiBicara.setName("CBFungsiBicara"); // NOI18N
        CBFungsiBicara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBFungsiBicaraActionPerformed(evt);
            }
        });
        panelGlass2.add(CBFungsiBicara);
        CBFungsiBicara.setBounds(270, 380, 150, 29);

        CBFungsiBahasa.setBackground(new java.awt.Color(255, 255, 255));
        CBFungsiBahasa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBFungsiBahasa.setText("Fungsi Bahasa / Laku");
        CBFungsiBahasa.setIconTextGap(10);
        CBFungsiBahasa.setName("CBFungsiBahasa"); // NOI18N
        CBFungsiBahasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBFungsiBahasaActionPerformed(evt);
            }
        });
        panelGlass2.add(CBFungsiBahasa);
        CBFungsiBahasa.setBounds(270, 410, 190, 29);

        CBFungsiMenelan.setBackground(new java.awt.Color(255, 255, 255));
        CBFungsiMenelan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBFungsiMenelan.setText("Fungsi Menelan");
        CBFungsiMenelan.setIconTextGap(10);
        CBFungsiMenelan.setName("CBFungsiMenelan"); // NOI18N
        CBFungsiMenelan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBFungsiMenelanActionPerformed(evt);
            }
        });
        panelGlass2.add(CBFungsiMenelan);
        CBFungsiMenelan.setBounds(270, 440, 200, 29);

        CBTerapiWicaraAnak.setBackground(new java.awt.Color(255, 255, 255));
        CBTerapiWicaraAnak.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBTerapiWicaraAnak.setText("Terapi Wicara Anak");
        CBTerapiWicaraAnak.setIconTextGap(10);
        CBTerapiWicaraAnak.setName("CBTerapiWicaraAnak"); // NOI18N
        CBTerapiWicaraAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTerapiWicaraAnakActionPerformed(evt);
            }
        });
        panelGlass2.add(CBTerapiWicaraAnak);
        CBTerapiWicaraAnak.setBounds(270, 470, 190, 29);

        LabelPsikologi.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelPsikologi.setText("Psikologi");
        LabelPsikologi.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        LabelPsikologi.setName("LabelPsikologi"); // NOI18N
        panelGlass2.add(LabelPsikologi);
        LabelPsikologi.setBounds(30, 440, 130, 23);

        CBPsikologiAnak.setBackground(new java.awt.Color(255, 255, 255));
        CBPsikologiAnak.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBPsikologiAnak.setText("Psikologi Anak");
        CBPsikologiAnak.setIconTextGap(10);
        CBPsikologiAnak.setName("CBPsikologiAnak"); // NOI18N
        CBPsikologiAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPsikologiAnakActionPerformed(evt);
            }
        });
        panelGlass2.add(CBPsikologiAnak);
        CBPsikologiAnak.setBounds(30, 470, 170, 29);

        CBPsikologiDewasa.setBackground(new java.awt.Color(255, 255, 255));
        CBPsikologiDewasa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBPsikologiDewasa.setText("Psikologi Dewasa");
        CBPsikologiDewasa.setIconTextGap(10);
        CBPsikologiDewasa.setName("CBPsikologiDewasa"); // NOI18N
        CBPsikologiDewasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPsikologiDewasaActionPerformed(evt);
            }
        });
        panelGlass2.add(CBPsikologiDewasa);
        CBPsikologiDewasa.setBounds(30, 500, 160, 29);

        LabelSosialMedik.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelSosialMedik.setText("Sosial Medik");
        LabelSosialMedik.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        LabelSosialMedik.setName("LabelSosialMedik"); // NOI18N
        panelGlass2.add(LabelSosialMedik);
        LabelSosialMedik.setBounds(270, 510, 170, 23);

        CBEvaluasiLingkungan.setBackground(new java.awt.Color(255, 255, 255));
        CBEvaluasiLingkungan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBEvaluasiLingkungan.setText("Evaluasi Lingkungan Rumah");
        CBEvaluasiLingkungan.setIconTextGap(10);
        CBEvaluasiLingkungan.setName("CBEvaluasiLingkungan"); // NOI18N
        CBEvaluasiLingkungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBEvaluasiLingkunganActionPerformed(evt);
            }
        });
        panelGlass2.add(CBEvaluasiLingkungan);
        CBEvaluasiLingkungan.setBounds(270, 540, 230, 29);

        CBEvaluasiEkonomi.setBackground(new java.awt.Color(255, 255, 255));
        CBEvaluasiEkonomi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBEvaluasiEkonomi.setText("Evaluasi Ekonomi");
        CBEvaluasiEkonomi.setIconTextGap(10);
        CBEvaluasiEkonomi.setName("CBEvaluasiEkonomi"); // NOI18N
        CBEvaluasiEkonomi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBEvaluasiEkonomiActionPerformed(evt);
            }
        });
        panelGlass2.add(CBEvaluasiEkonomi);
        CBEvaluasiEkonomi.setBounds(270, 570, 160, 29);

        CBEvaluasiPekerjaan.setBackground(new java.awt.Color(255, 255, 255));
        CBEvaluasiPekerjaan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBEvaluasiPekerjaan.setText("Evaluasi Pekerjaan");
        CBEvaluasiPekerjaan.setIconTextGap(10);
        CBEvaluasiPekerjaan.setName("CBEvaluasiPekerjaan"); // NOI18N
        CBEvaluasiPekerjaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBEvaluasiPekerjaanActionPerformed(evt);
            }
        });
        panelGlass2.add(CBEvaluasiPekerjaan);
        CBEvaluasiPekerjaan.setBounds(270, 600, 170, 29);

        LabelOrtotikProstetik.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LabelOrtotikProstetik.setText("Ortotik Prostetik");
        LabelOrtotikProstetik.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        LabelOrtotikProstetik.setName("LabelOrtotikProstetik"); // NOI18N
        panelGlass2.add(LabelOrtotikProstetik);
        LabelOrtotikProstetik.setBounds(30, 540, 190, 23);

        CBPembuatanAlatBantu.setBackground(new java.awt.Color(255, 255, 255));
        CBPembuatanAlatBantu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBPembuatanAlatBantu.setText("Pembuatan Alat Bantu");
        CBPembuatanAlatBantu.setIconTextGap(10);
        CBPembuatanAlatBantu.setName("CBPembuatanAlatBantu"); // NOI18N
        CBPembuatanAlatBantu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPembuatanAlatBantuActionPerformed(evt);
            }
        });
        panelGlass2.add(CBPembuatanAlatBantu);
        CBPembuatanAlatBantu.setBounds(30, 570, 190, 29);

        CBPembuatanAlatAnggotaTiruan.setBackground(new java.awt.Color(255, 255, 255));
        CBPembuatanAlatAnggotaTiruan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        CBPembuatanAlatAnggotaTiruan.setText("Pembuatan Alat Anggota Tiruan");
        CBPembuatanAlatAnggotaTiruan.setIconTextGap(10);
        CBPembuatanAlatAnggotaTiruan.setName("CBPembuatanAlatAnggotaTiruan"); // NOI18N
        CBPembuatanAlatAnggotaTiruan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBPembuatanAlatAnggotaTiruanActionPerformed(evt);
            }
        });
        panelGlass2.add(CBPembuatanAlatAnggotaTiruan);
        CBPembuatanAlatAnggotaTiruan.setBounds(30, 600, 240, 29);

        BtnLihatRekap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/open.png"))); // NOI18N
        BtnLihatRekap.setMnemonic('K');
        BtnLihatRekap.setText("Lihat Rekap");
        BtnLihatRekap.setToolTipText("Alt+K");
        BtnLihatRekap.setIconTextGap(10);
        BtnLihatRekap.setName("BtnLihatRekap"); // NOI18N
        BtnLihatRekap.setPreferredSize(new java.awt.Dimension(85, 30));
        BtnLihatRekap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLihatRekapActionPerformed(evt);
            }
        });
        BtnLihatRekap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnLihatRekapKeyPressed(evt);
            }
        });
        panelGlass2.add(BtnLihatRekap);
        BtnLihatRekap.setBounds(980, 70, 110, 30);

        internalFrame1.add(panelGlass2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

        
    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        if (TNoRwCari.getText()!=null && !TNoRwCari.getText().trim().isEmpty()) {
            muatData();
        }
    }
                                 
    private void BtnSimpanTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanTBActionPerformed
        simpanTB();
    }//GEN-LAST:event_BtnSimpanTBActionPerformed

    private void CBGaitAnalyzerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBGaitAnalyzerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBGaitAnalyzerActionPerformed

    private void TNoRwCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TNoRwCariMouseClicked
        
    }//GEN-LAST:event_TNoRwCariMouseClicked

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        dispose();        
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void CBEmgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBEmgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBEmgActionPerformed

    private void CBUroDinamicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBUroDinamicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBUroDinamicActionPerformed

    private void CBSideBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBSideBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBSideBackActionPerformed

    private void CBENTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBENTreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBENTreeActionPerformed

    private void CBSpyrometerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBSpyrometerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBSpyrometerActionPerformed

    private void CBStaticBicycleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBStaticBicycleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBStaticBicycleActionPerformed

    private void CBTreadMillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTreadMillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBTreadMillActionPerformed

    private void CBBodyPlatysmografActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBBodyPlatysmografActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBBodyPlatysmografActionPerformed

    private void CBLatihanFisikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBLatihanFisikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBLatihanFisikActionPerformed

    private void CBAktinoterapiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBAktinoterapiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBAktinoterapiActionPerformed

    private void CBElektroterapiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBElektroterapiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBElektroterapiActionPerformed

    private void CBHidroterapiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBHidroterapiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBHidroterapiActionPerformed

    private void CBTraksiLumbalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTraksiLumbalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBTraksiLumbalActionPerformed

    private void CBFisioterapiAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBFisioterapiAnakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBFisioterapiAnakActionPerformed

    private void CBSnoosienRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBSnoosienRoomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBSnoosienRoomActionPerformed

    private void CBSensoriIntegrasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBSensoriIntegrasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBSensoriIntegrasiActionPerformed

    private void CBLatihanAktivitasKehidupanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBLatihanAktivitasKehidupanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBLatihanAktivitasKehidupanActionPerformed

    private void CBProperBodyMekanikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBProperBodyMekanikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBProperBodyMekanikActionPerformed

    private void CBPembuatanAlatLontarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPembuatanAlatLontarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPembuatanAlatLontarActionPerformed

    private void CBAnalisaPersiapanKerjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBAnalisaPersiapanKerjaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBAnalisaPersiapanKerjaActionPerformed

    private void CBLatihanRelaksasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBLatihanRelaksasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBLatihanRelaksasiActionPerformed

    private void CBAnalisadanIntervensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTreadMill1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBTreadMill1ActionPerformed

    private void CBOkupasiterapiAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBBodyPlatysmograf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBBodyPlatysmograf1ActionPerformed

    private void CBFungsiBicaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBFungsiBicaraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBFungsiBicaraActionPerformed

    private void CBFungsiBahasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVFungsiBahasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CVFungsiBahasaActionPerformed

    private void CBFungsiMenelanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBFungsiMenelanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBFungsiMenelanActionPerformed

    private void CBTerapiWicaraAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTerapiWicaraAnakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBTerapiWicaraAnakActionPerformed

    private void CBPsikologiAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPsikologiAnakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPsikologiAnakActionPerformed

    private void CBPsikologiDewasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPsikologiDewasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPsikologiDewasaActionPerformed

    private void CBEvaluasiLingkunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBEvaluasiLingkunganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBEvaluasiLingkunganActionPerformed

    private void CBEvaluasiEkonomiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBEvaluasiEkonomiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBEvaluasiEkonomiActionPerformed

    private void CBEvaluasiPekerjaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBEvaluasiPekerjaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBEvaluasiPekerjaanActionPerformed

    private void CBPembuatanAlatBantuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPembuatanAlatBantuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPembuatanAlatBantuActionPerformed

    private void CBPembuatanAlatAnggotaTiruanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBPembuatanAlatAnggotaTiruanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBPembuatanAlatAnggotaTiruanActionPerformed

    private void BtnLihatRekapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLihatRekapActionPerformed
        dispose();
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        DlgRl313RehabilitasiMedik RL13=new DlgRl313RehabilitasiMedik(null,false);
//        RL13.setSize(internalFrame1.getWidth(),internalFrame1.getHeight());
        RL13.setLocationRelativeTo(internalFrame1);               
        RL13.setVisible(true);
        this.setCursor(Cursor.getDefaultCursor());  
    }//GEN-LAST:event_BtnLihatRekapActionPerformed

    private void BtnLihatRekapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnLihatRekapKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnLihatRekapKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            CeklisPelayananRehabMedik dialog = new CeklisPelayananRehabMedik(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Button BtnLihatRekap;
    private widget.Button BtnSimpanTB;
    private javax.swing.JCheckBox CBAktinoterapi;
    private javax.swing.JCheckBox CBAnalisaPersiapanKerja;
    private javax.swing.JCheckBox CBAnalisadanIntervensi;
    private javax.swing.JCheckBox CBBodyPlatysmograf;
    private javax.swing.JCheckBox CBENTree;
    private javax.swing.JCheckBox CBElektroterapi;
    private javax.swing.JCheckBox CBEmg;
    private javax.swing.JCheckBox CBEvaluasiEkonomi;
    private javax.swing.JCheckBox CBEvaluasiLingkungan;
    private javax.swing.JCheckBox CBEvaluasiPekerjaan;
    private javax.swing.JCheckBox CBFisioterapiAnak;
    private javax.swing.JCheckBox CBFungsiBahasa;
    private javax.swing.JCheckBox CBFungsiBicara;
    private javax.swing.JCheckBox CBFungsiMenelan;
    private javax.swing.JCheckBox CBGaitAnalyzer;
    private javax.swing.JCheckBox CBHidroterapi;
    private javax.swing.JCheckBox CBLatihanAktivitasKehidupan;
    private javax.swing.JCheckBox CBLatihanFisik;
    private javax.swing.JCheckBox CBLatihanRelaksasi;
    private javax.swing.JCheckBox CBOkupasiterapiAnak;
    private javax.swing.JCheckBox CBPembuatanAlatAnggotaTiruan;
    private javax.swing.JCheckBox CBPembuatanAlatBantu;
    private javax.swing.JCheckBox CBPembuatanAlatLontar;
    private javax.swing.JCheckBox CBProperBodyMekanik;
    private javax.swing.JCheckBox CBPsikologiAnak;
    private javax.swing.JCheckBox CBPsikologiDewasa;
    private javax.swing.JCheckBox CBSensoriIntegrasi;
    private javax.swing.JCheckBox CBSideBack;
    private javax.swing.JCheckBox CBSnoosienRoom;
    private javax.swing.JCheckBox CBSpyrometer;
    private javax.swing.JCheckBox CBStaticBicycle;
    private javax.swing.JCheckBox CBTerapiWicaraAnak;
    private javax.swing.JCheckBox CBTraksiLumbal;
    private javax.swing.JCheckBox CBTreadMill;
    private javax.swing.JCheckBox CBUroDinamic;
    private widget.Label LabelFisioterapi;
    private widget.Label LabelMedis;
    private widget.Label LabelOkupasiterapi;
    private widget.Label LabelOrtotikProstetik;
    private widget.Label LabelPsikologi;
    private widget.Label LabelSosialMedik;
    private widget.Label LabelTerapiWicara;
    private widget.Label LblIdentitas;
    private widget.TextBox TNoRwCari;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel22;
    private widget.Label jLabel27;
    private widget.Label jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private widget.panelisi panelGlass2;
    private widget.panelisi panelGlass8;
    // End of variables declaration//GEN-END:variables

private 
    void simpanTB() {
        final String noRawat = TNoRwCari.getText() == null ? "" : TNoRwCari.getText().trim();
        if (noRawat.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No. Rawat belum diisi.");
            return;
        }
        java.util.Map<String, javax.swing.JCheckBox> map = mapItem();
        try {
            koneksi.setAutoCommit(false);
            try (PreparedStatement ps = koneksi.prepareStatement("DELETE FROM rehab_ceklis WHERE no_rawat=?")) {
                ps.setString(1, noRawat);
                ps.executeUpdate();
            }
            try (PreparedStatement ps = koneksi.prepareStatement(
                    "INSERT INTO rehab_ceklis(no_rawat,item_code,jumlah) VALUES(?,?,1)")) {
                for (java.util.Map.Entry<String, javax.swing.JCheckBox> e : map.entrySet()) {
                    javax.swing.JCheckBox cb = e.getValue();
                    if (cb != null && cb.isSelected()) {
                        ps.setString(1, noRawat);
                        ps.setString(2, e.getKey());
                        ps.addBatch();
                    }
                }
                ps.executeBatch();
            }
            koneksi.commit();
            JOptionPane.showMessageDialog(null, "Ceklis tersimpan.");
            muatData(); // refresh checkbox (idempotent)
        } catch (Exception ex) {
            try { koneksi.rollback(); } catch (Exception ig) {}
            JOptionPane.showMessageDialog(null, "Gagal menyimpan ceklis: " + ex.getMessage());
        } finally {
            try { koneksi.setAutoCommit(true); } catch (Exception ig) {}
        }
        dispose();
    }


    private static class string {

        public string() {
        }
    }
    


    /**
     * Set No. Rawat dari luar form dan langsung memuat data jika ada.
     */
    
    /**
     * Peta kode item -> JCheckBox sesuai komponen pada form.
     * Gunakan LinkedHashMap agar urutan tetap.
     */
    private java.util.Map<String, javax.swing.JCheckBox> mapItem() {
        java.util.Map<String, javax.swing.JCheckBox> m = new java.util.LinkedHashMap<>();
        // Medis
        m.put("1.1", CBGaitAnalyzer);
        m.put("1.2", CBEmg);
        m.put("1.3", CBUroDinamic);
        m.put("1.4", CBSideBack);
        m.put("1.5", CBENTree);
        m.put("1.6", CBSpyrometer);
        m.put("1.7", CBStaticBicycle);
        m.put("1.8", CBTreadMill);
        m.put("1.9", CBBodyPlatysmograf);
        // Fisioterapi
        m.put("2.1", CBLatihanFisik);
        m.put("2.2", CBAktinoterapi);
        m.put("2.3", CBElektroterapi);
        m.put("2.4", CBHidroterapi);
        m.put("2.5", CBTraksiLumbal);
        m.put("2.6", CBFisioterapiAnak);
        // Okupasiterapi
        m.put("3.1", CBSnoosienRoom);
        m.put("3.2", CBSensoriIntegrasi);
        m.put("3.3", CBLatihanAktivitasKehidupan);
        m.put("3.4", CBProperBodyMekanik);
        m.put("3.5", CBPembuatanAlatLontar);
        m.put("3.6", CBAnalisaPersiapanKerja);
        m.put("3.7", CBLatihanRelaksasi);
        // Catatan: di file ini nama komponen untuk "Analisa & Intervensi..." dan "Okupasiterapi Anak"
        // ialah CBTreadMill1 dan CBBodyPlatysmograf1
        m.put("3.8", CBAnalisadanIntervensi);
        m.put("3.9", CBOkupasiterapiAnak);
        // Terapi Wicara
        m.put("4.1", CBFungsiBicara);
        m.put("4.2", CBFungsiBahasa);
        m.put("4.3", CBFungsiMenelan);
        m.put("4.4", CBTerapiWicaraAnak);
        // Psikologi
        m.put("5.1", CBPsikologiAnak);
        m.put("5.2", CBPsikologiDewasa);
        // Sosial Medik
        m.put("6.1", CBEvaluasiLingkungan);
        m.put("6.2", CBEvaluasiEkonomi);
        m.put("6.3", CBEvaluasiPekerjaan);
        // Ortotik Prostetik
        m.put("7.1", CBPembuatanAlatBantu);
        m.put("7.2", CBPembuatanAlatAnggotaTiruan);
        return m;
    }
public void setNoRawat(String noRawat) {
        if (noRawat == null) noRawat = "";
        TNoRwCari.setText(noRawat.trim());
        if (!noRawat.trim().isEmpty()) {
            muatData();
            updateIdentitasPasien();

        }
    }

    /**
     * Muat data dari tabel terindikasi_tb berdasarkan no_rawat
     * dan sinkronkan ke UI.
     */
    
    private void muatData() {
        String noRawat = TNoRwCari.getText() == null ? "" : TNoRwCari.getText().trim();
        java.util.Map<String, javax.swing.JCheckBox> map = mapItem();
        // reset semua checkbox
        for (javax.swing.JCheckBox cb : map.values()) { if (cb != null) cb.setSelected(false); }
        if (noRawat.isEmpty()) {
            updateIdentitasPasien();
            return;
        }
        try (PreparedStatement ps = koneksi.prepareStatement(
                "SELECT item_code FROM rehab_ceklis WHERE no_rawat=?")) {
            ps.setString(1, noRawat);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    String code = rs.getString(1);
                    javax.swing.JCheckBox cb = map.get(code);
                    if (cb != null) cb.setSelected(true);
                }
            }
        } catch (Exception e) {
            System.out.println("Notifikasi muatData : " + e.getMessage());
        }
        updateIdentitasPasien();
    }


private void updateIdentitasPasien() {
    String noRawat = TNoRwCari.getText() != null ? TNoRwCari.getText().trim() : "";
    if (noRawat.isEmpty()) {
        if (LblIdentitas != null) LblIdentitas.setText("");
        return;
    }

    String sql = "SELECT p.no_rkm_medis, p.nm_pasien, rp.umurdaftar, rp.sttsumur " +
                 "FROM reg_periksa rp " +
                 "JOIN pasien p ON p.no_rkm_medis = rp.no_rkm_medis " +
                 "WHERE rp.no_rawat = ? " +
                 "LIMIT 1";

    try (PreparedStatement ps = koneksi.prepareStatement(sql)) {
        ps.setString(1, noRawat);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                String noRM   = rs.getString("no_rkm_medis");
                String nama   = rs.getString("nm_pasien");
                String umur   = rs.getString("umurdaftar");
                String stts   = rs.getString("sttsumur");

                // Rakit teks umur: tampil abu-abu
                    String umurFmt = "";
                    if (umur != null && !umur.trim().isEmpty() && stts != null && !stts.trim().isEmpty()) {
                        umurFmt = " <font color='#888888'> [ " + umur.trim() + " " + stts.trim() + " ]</font>";
                    }

                    // Versi A: seluruh baris tetap bold, umur abu-abu (bold + abu-abu)
                    String html = "<html><b>"
                            + (noRM == null ? "" : noRM) + "&nbsp;&nbsp;"
                            + (nama == null ? "" : nama)
                            + umurFmt
                            + "</b></html>";
                    LblIdentitas.setText(html);

                if (LblIdentitas != null) {
                    LblIdentitas.setText(html);
                }
            } else {
                if (LblIdentitas != null) LblIdentitas.setText("");
            }
        }
    } catch (Exception e) {
        System.out.println("Notifikasi updateIdentitasPasien : " + e.getMessage());
        if (LblIdentitas != null) LblIdentitas.setText("");
    }
}

}
