/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

 /*
 * DlgLhtBiaya.java
 *
 * Created on 12 Jul 10, 16:21:34
 */
package laporan;

import fungsi.WarnaTable;
import fungsi.batasInput;
import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import fungsi.akses;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author perpustakaan
 */
public final class DlgRl31IndikatorPelayanan extends javax.swing.JDialog {

    private final DefaultTableModel tabMode;
    private Connection koneksi = koneksiDB.condb();
    private sekuel Sequel = new sekuel();
    private validasi Valid = new validasi();
    private PreparedStatement ps;
    private ResultSet rs;
    private int i = 0; 
            ;

    /**
     * Creates new form DlgLhtBiaya
     *
     * @param parent
     * @param modal
     */
    public DlgRl31IndikatorPelayanan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocation(8, 1);
        setSize(885, 674);

        Object[] rowRwJlDr = {
            "No.","Jenis Pelayanan", "BOR", "ALOS", 
            "BTO", "TOI", "NDR", "GDR"
        };
        tabMode = new DefaultTableModel(null, rowRwJlDr) {
            @Override
            public boolean isCellEditable(int rowIndex, int colIndex) {
                return false;
            }
        };
        tbBangsal.setModel(tabMode);
        //tbBangsal.setDefaultRenderer(Object.class, new WarnaTable(jPanel2.getBackground(),tbBangsal.getBackground()));
        tbBangsal.setPreferredScrollableViewportSize(new Dimension(500, 500));
        tbBangsal.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        int[] lebarKolom = {40, 165, 80, 80, 80, 80, 80, 80};
        for (i = 0; i < lebarKolom.length; i++) {
            TableColumn column = tbBangsal.getColumnModel().getColumn(i);
            column.setPreferredWidth(lebarKolom[i]);
        }
        tbBangsal.setDefaultRenderer(Object.class, new WarnaTable());

        TCari.setDocument(new batasInput((byte) 100).getKata(TCari));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        Scroll = new widget.ScrollPane();
        tbBangsal = new widget.Table();
        panelGlass5 = new widget.panelisi();
        label11 = new widget.Label();
        Tgl1 = new widget.Tanggal();
        label18 = new widget.Label();
        Tgl2 = new widget.Tanggal();
        jLabel6 = new widget.Label();
        TCari = new widget.TextBox();
        BtnCari = new widget.Button();
        BtnAll = new widget.Button();
        jLabel7 = new widget.Label();
        BtnPrint = new widget.Button();
        BtnKeluar = new widget.Button();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), " ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        Scroll.setName("Scroll"); // NOI18N
        Scroll.setOpaque(true);

        tbBangsal.setName("tbBangsal"); // NOI18N
        Scroll.setViewportView(tbBangsal);

        internalFrame1.add(Scroll, java.awt.BorderLayout.CENTER);

        panelGlass5.setName("panelGlass5"); // NOI18N
        panelGlass5.setPreferredSize(new java.awt.Dimension(55, 55));
        panelGlass5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        label11.setText("Tanggal :");
        label11.setName("label11"); // NOI18N
        label11.setPreferredSize(new java.awt.Dimension(50, 23));
        panelGlass5.add(label11);

        Tgl1.setDisplayFormat("dd-MM-yyyy");
        Tgl1.setName("Tgl1"); // NOI18N
        Tgl1.setPreferredSize(new java.awt.Dimension(90, 23));
        panelGlass5.add(Tgl1);

        label18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label18.setText("s.d.");
        label18.setName("label18"); // NOI18N
        label18.setPreferredSize(new java.awt.Dimension(25, 23));
        panelGlass5.add(label18);

        Tgl2.setDisplayFormat("dd-MM-yyyy");
        Tgl2.setName("Tgl2"); // NOI18N
        Tgl2.setPreferredSize(new java.awt.Dimension(90, 23));
        panelGlass5.add(Tgl2);

        jLabel6.setText("Key Word :");
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(60, 23));
        panelGlass5.add(jLabel6);

        TCari.setName("TCari"); // NOI18N
        TCari.setPreferredSize(new java.awt.Dimension(155, 23));
        TCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TCariKeyPressed(evt);
            }
        });
        panelGlass5.add(TCari);

        BtnCari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/accept.png"))); // NOI18N
        BtnCari.setMnemonic('2');
        BtnCari.setToolTipText("Alt+2");
        BtnCari.setName("BtnCari"); // NOI18N
        BtnCari.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCariActionPerformed(evt);
            }
        });
        BtnCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnCariKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnCari);

        BtnAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Search-16x16.png"))); // NOI18N
        BtnAll.setMnemonic('M');
        BtnAll.setToolTipText("Alt+M");
        BtnAll.setName("BtnAll"); // NOI18N
        BtnAll.setPreferredSize(new java.awt.Dimension(28, 23));
        BtnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAllActionPerformed(evt);
            }
        });
        BtnAll.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnAllKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnAll);

        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(30, 23));
        panelGlass5.add(jLabel7);

        BtnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/b_print.png"))); // NOI18N
        BtnPrint.setMnemonic('T');
        BtnPrint.setText("Cetak");
        BtnPrint.setToolTipText("Alt+T");
        BtnPrint.setName("BtnPrint"); // NOI18N
        BtnPrint.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPrintActionPerformed(evt);
            }
        });
        BtnPrint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnPrintKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnPrint);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass5.add(BtnKeluar);

        internalFrame1.add(panelGlass5, java.awt.BorderLayout.PAGE_END);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48x48/report24.png"))); // NOI18N
        jLabel1.setText("RL 3.1  Indikator Pelayanan ");
        jLabel1.setIconTextGap(10);
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1);

        internalFrame1.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPrintActionPerformed
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (tabMode.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Maaf, data sudah habis. Tidak ada data yang bisa anda print...!!!!");
        } else {
            try {
                File f = new File("rl31.html");
                try (BufferedWriter bw = new BufferedWriter(new FileWriter(f))) {
                    bw.write("<html><head><title>RL 3.1 Indikator Pelayanan</title>" +
                             "<style>body{font-family:Tahoma,Arial,sans-serif;font-size:11px;}" +
                             "table{border-collapse:collapse;width:100%;}th,td{border:1px solid #999;padding:4px;}" +
                             "th{text-align:center;background:#f4f4f4;}td.angka{text-align:right;}" +
                             "h2,h3,p{text-align:center;margin:3px;}</style></head><body>");
                    bw.write("<h2>" + escapeHtml(akses.getnamars()) + "</h2>");
                    bw.write("<p>" + escapeHtml(akses.getalamatrs()) + ", " + escapeHtml(akses.getkabupatenrs()) + ", " + escapeHtml(akses.getpropinsirs()) + "</p>");
                    bw.write("<p>" + escapeHtml(akses.getkontakrs()) + ", E-mail : " + escapeHtml(akses.getemailrs()) + "</p>");
                    bw.write("<br><h3>FORMULIR RL 3.1 - INDIKATOR PELAYANAN</h3>");
                    bw.write("<p>PERIODE " + escapeHtml(Tgl1.getSelectedItem() + " s.d. " + Tgl2.getSelectedItem()) + "</p><br>");
                    bw.write("<p style='text-align:left'><b>Model 1: Sesuai Juknis SIRS 6.3</b></p>");
                    bw.write("<table><tr><th>No.</th><th>Jenis Pelayanan</th><th>BOR</th><th>ALOS</th><th>BTO</th><th>TOI</th><th>NDR</th><th>GDR</th></tr>");
                    boolean masukModelRingkas = false;
                    StringBuilder htmlModelRingkas = new StringBuilder();
                    for (int r = 0; r < tabMode.getRowCount(); r++) {
                        String no = tabMode.getValueAt(r, 0).toString();
                        String jenis = tabMode.getValueAt(r, 1).toString();
                        if (no.equals("") && jenis.equals("MODEL 2 / RINGKAS")) {
                            masukModelRingkas = true;
                            continue;
                        }
                        StringBuilder baris = new StringBuilder();
                        baris.append("<tr>");
                        baris.append("<td align='center'>").append(escapeHtml(no)).append("</td>");
                        baris.append("<td>").append(escapeHtml(jenis)).append("</td>");
                        for (int c = 2; c <= 7; c++) {
                            baris.append("<td class='angka'>").append(escapeHtml(tabMode.getValueAt(r, c).toString())).append("</td>");
                        }
                        baris.append("</tr>");
                        if (masukModelRingkas) {
                            htmlModelRingkas.append(baris);
                        } else {
                            bw.write(baris.toString());
                        }
                    }
                    bw.write("</table><br>");
                    if (htmlModelRingkas.length() > 0) {
                        bw.write("<p style='text-align:left'><b>Model 2: Rekap Ringkas 1 Baris Sesuai Periode Filter</b></p>");
                        bw.write("<table><tr><th>No.</th><th>Jenis Pelayanan</th><th>BOR</th><th>ALOS</th><th>BTO</th><th>TOI</th><th>NDR</th><th>GDR</th></tr>");
                        bw.write(htmlModelRingkas.toString());
                        bw.write("</table><br>");
                    }
                    bw.write("<p style='text-align:left'>Catatan: BOR dalam persen (%), ALOS/TOI dalam hari, BTO dalam kali, NDR/GDR per 1000 pasien keluar. Model 2 memakai perhitungan total seluruh tempat tidur rawat inap, bukan rata-rata antarbaris.</p>");
                    bw.write("</body></html>");
                }
                Desktop.getDesktop().browse(f.toURI());
            } catch (Exception e) {
                System.out.println("Notifikasi Cetak RL 3.1 : " + e);
                JOptionPane.showMessageDialog(null, "Gagal membuat cetakan RL 3.1 : " + e.getMessage());
            }
        }
        this.setCursor(Cursor.getDefaultCursor());
}//GEN-LAST:event_BtnPrintActionPerformed

    private void BtnPrintKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnPrintKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnPrintActionPerformed(null);
        } else {
            //Valid.pindah(evt, BtnHapus, BtnAll);
        }
}//GEN-LAST:event_BtnPrintKeyPressed

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            dispose();
        } else {
            Valid.pindah(evt, BtnKeluar, TCari);
        }
}//GEN-LAST:event_BtnKeluarKeyPressed

private void BtnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCariActionPerformed
    tampil();
}//GEN-LAST:event_BtnCariActionPerformed

private void BtnCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnCariKeyPressed
    if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        tampil();
        this.setCursor(Cursor.getDefaultCursor());
    } else {
        Valid.pindah(evt, TCari, BtnPrint);
    }
}//GEN-LAST:event_BtnCariKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        tampil();
    }//GEN-LAST:event_formWindowOpened

    private void TCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TCariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            BtnCariActionPerformed(null);
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_DOWN) {
            BtnCari.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_PAGE_UP) {
            BtnKeluar.requestFocus();
        }
    }//GEN-LAST:event_TCariKeyPressed

    private void BtnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAllActionPerformed
        TCari.setText("");
        tampil();
    }//GEN-LAST:event_BtnAllActionPerformed

    private void BtnAllKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnAllKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            BtnAllActionPerformed(null);
        } else {

        }
    }//GEN-LAST:event_BtnAllKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        tampil();

    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            DlgRl31IndikatorPelayanan dialog = new DlgRl31IndikatorPelayanan(new javax.swing.JFrame(), true);           
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnAll;
    private widget.Button BtnCari;
    private widget.Button BtnKeluar;
    private widget.Button BtnPrint;
    private widget.ScrollPane Scroll;
    private widget.TextBox TCari;
    private widget.Tanggal Tgl1;
    private widget.Tanggal Tgl2;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JLabel jLabel1;
    private widget.Label jLabel6;
    private widget.Label jLabel7;
    private javax.swing.JPanel jPanel1;
    private widget.Label label11;
    private widget.Label label18;
    private widget.panelisi panelGlass5;
    private widget.Table tbBangsal;
    // End of variables declaration//GEN-END:variables

private void tampil() {
    Valid.tabelKosong(tabMode);

    try {
        String tglAwal = Valid.SetTgl(Tgl1.getSelectedItem() + "");
        String tglAkhir = Valid.SetTgl(Tgl2.getSelectedItem() + "");

        String[][] jenisPelayanan = {
            {"1", "Non Intensif", "NON_INTENSIF"},
            {"2", "ICU", "ICU"},
            {"3", "NICU", "NICU"},
            {"4", "PICU", "PICU"},
            {"5", "Intensif lainnya", "INTENSIF_LAINNYA"}
        };

        double[] jumlahBOR = new double[1];
        double[] jumlahALOS = new double[1];
        double[] jumlahBTO = new double[1];
        double[] jumlahTOI = new double[1];
        double[] jumlahNDR = new double[1];
        double[] jumlahGDR = new double[1];
        int[] isiBOR = new int[1];
        int[] isiALOS = new int[1];
        int[] isiBTO = new int[1];
        int[] isiTOI = new int[1];
        int[] isiNDR = new int[1];
        int[] isiGDR = new int[1];

        int jumlahHariPeriode = getJumlahHariDalamPeriode(tglAwal, tglAkhir);

        for (String[] jp : jenisPelayanan) {
            DataIndikator data = hitungIndikator(jp[2], tglAwal, tglAkhir, jumlahHariPeriode);

            if (data.tt > 0) {
                jumlahBOR[0] += data.bor;
                isiBOR[0]++;
                jumlahBTO[0] += data.bto;
                isiBTO[0]++;
            }
            if (data.pasienKeluar > 0) {
                jumlahALOS[0] += data.alos;
                isiALOS[0]++;
                jumlahNDR[0] += data.ndr;
                isiNDR[0]++;
                jumlahGDR[0] += data.gdr;
                isiGDR[0]++;
            }
            if (data.tt > 0 && data.pasienKeluar > 0) {
                jumlahTOI[0] += data.toi;
                isiTOI[0]++;
            }

            tambahBaris(jp[0], jp[1], data.bor, data.alos, data.bto, data.toi, data.ndr, data.gdr);
        }

        tambahBaris(
            "77",
            "Rata-rata",
            isiBOR[0] > 0 ? jumlahBOR[0] / isiBOR[0] : 0,
            isiALOS[0] > 0 ? jumlahALOS[0] / isiALOS[0] : 0,
            isiBTO[0] > 0 ? jumlahBTO[0] / isiBTO[0] : 0,
            isiTOI[0] > 0 ? jumlahTOI[0] / isiTOI[0] : 0,
            isiNDR[0] > 0 ? jumlahNDR[0] / isiNDR[0] : 0,
            isiGDR[0] > 0 ? jumlahGDR[0] / isiGDR[0] : 0
        );

        // Model 2: rekap ringkas satu baris sesuai periode filter.
        // Ini untuk kebutuhan pembanding/internal, sedangkan model 1 di atas tetap mengikuti baris Juknis.
        DataIndikator dataTotal = hitungIndikator("SEMUA", tglAwal, tglAkhir, jumlahHariPeriode);
        tambahPemisahModelRingkas();
        tambahBaris(
            "1",
            getLabelPeriode(tglAwal, tglAkhir),
            dataTotal.bor,
            dataTotal.alos,
            dataTotal.bto,
            dataTotal.toi,
            dataTotal.ndr,
            dataTotal.gdr
        );
    } catch (Exception e) {
        System.out.println("Error tampil RL 3.1: " + e);
    }
}

private void tambahBaris(String no, String jenisPelayanan, double bor, double alos, double bto, double toi, double ndr, double gdr) {
    String kataKunci = TCari.getText().trim().toLowerCase();
    if (!kataKunci.equals("") && !(no.toLowerCase().contains(kataKunci) || jenisPelayanan.toLowerCase().contains(kataKunci))) {
        return;
    }

    tabMode.addRow(new Object[]{
        no,
        jenisPelayanan,
        angka(bor),
        angka(alos),
        angka(bto),
        angka(toi),
        angka(ndr),
        angka(gdr)
    });
}

private void tambahPemisahModelRingkas() {
    String kataKunci = TCari.getText().trim();
    if (!kataKunci.equals("")) {
        return;
    }
    tabMode.addRow(new Object[]{
        "",
        "MODEL 2 / RINGKAS",
        "",
        "",
        "",
        "",
        "",
        ""
    });
}

private DataIndikator hitungIndikator(String kategori, String tglAwal, String tglAkhir, int jumlahHariPeriode) throws SQLException {
    DataIndikator data = new DataIndikator();
    data.tt = getJumlahTempatTidur(kategori);
    data.hariPerawatan = getJumlahHariPerawatan(kategori, tglAwal, tglAkhir);
    data.lamaDirawat = getJumlahLamaDirawat(kategori, tglAwal, tglAkhir);
    data.pasienKeluar = getJumlahPasienKeluarHidupMati(kategori, tglAwal, tglAkhir);
    data.matiLebih48 = getJumlahPasienMatiLebih48Jam(kategori, tglAwal, tglAkhir);
    data.matiTotal = getJumlahPasienMati(kategori, tglAwal, tglAkhir);

    data.bor = data.tt > 0 && jumlahHariPeriode > 0 ? (double) data.hariPerawatan / (data.tt * jumlahHariPeriode) * 100 : 0;
    data.alos = data.pasienKeluar > 0 ? (double) data.lamaDirawat / data.pasienKeluar : 0;
    data.bto = data.tt > 0 ? (double) data.pasienKeluar / data.tt : 0;
    data.toi = data.pasienKeluar > 0 && data.tt > 0 ? (double) ((data.tt * jumlahHariPeriode) - data.hariPerawatan) / data.pasienKeluar : 0;
    data.ndr = data.pasienKeluar > 0 ? (double) data.matiLebih48 / data.pasienKeluar * 1000 : 0;
    data.gdr = data.pasienKeluar > 0 ? (double) data.matiTotal / data.pasienKeluar * 1000 : 0;

    return data;
}

private int getJumlahTempatTidur(String kategori) throws SQLException {
    String sql = "SELECT COUNT(*) AS total " +
                 "FROM kamar k " +
                 "INNER JOIN bangsal b ON b.kd_bangsal = k.kd_bangsal " +
                 "WHERE k.statusdata = '1' AND " + kondisiKategori(kategori);
    try (PreparedStatement ps = koneksi.prepareStatement(sql);
         ResultSet rs = ps.executeQuery()) {
        if (rs.next()) {
            return rs.getInt("total");
        }
    }
    return 0;
}

private int getJumlahHariPerawatan(String kategori, String tglAwal, String tglAkhir) throws SQLException {
    String sql = "SELECT IFNULL(SUM(GREATEST(DATEDIFF(LEAST(IF(ki.tgl_keluar IS NULL OR ki.tgl_keluar = '0000-00-00', ?, ki.tgl_keluar), ?), GREATEST(ki.tgl_masuk, ?)) + 1, 0)), 0) AS total " +
                 "FROM kamar_inap ki " +
                 "INNER JOIN reg_periksa rp ON rp.no_rawat = ki.no_rawat " +
                 "INNER JOIN kamar k ON k.kd_kamar = ki.kd_kamar " +
                 "INNER JOIN bangsal b ON b.kd_bangsal = k.kd_bangsal " +
                 "WHERE rp.status_lanjut = 'Ranap' " +
                 "AND rp.stts <> 'Batal' " +
                 "AND ki.tgl_masuk <= ? " +
                 "AND (ki.tgl_keluar IS NULL OR ki.tgl_keluar = '0000-00-00' OR ki.tgl_keluar >= ?) " +
                 "AND " + kondisiKategori(kategori);
    try (PreparedStatement ps = koneksi.prepareStatement(sql)) {
        ps.setString(1, tglAkhir);
        ps.setString(2, tglAkhir);
        ps.setString(3, tglAwal);
        ps.setString(4, tglAkhir);
        ps.setString(5, tglAwal);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                return rs.getInt("total");
            }
        }
    }
    return 0;
}

private int getJumlahLamaDirawat(String kategori, String tglAwal, String tglAkhir) throws SQLException {
    String sql = "SELECT IFNULL(SUM(GREATEST(DATEDIFF(x.tgl_keluar, x.tgl_masuk_pertama), 1)), 0) AS total " +
                 "FROM ( " +
                 "SELECT rp.no_rawat, MAX(ki.tgl_keluar) AS tgl_keluar, MIN(km.tgl_masuk_pertama) AS tgl_masuk_pertama " +
                 "FROM reg_periksa rp " +
                 "INNER JOIN kamar_inap ki ON rp.no_rawat = ki.no_rawat " +
                 "INNER JOIN kamar k ON k.kd_kamar = ki.kd_kamar " +
                 "INNER JOIN bangsal b ON b.kd_bangsal = k.kd_bangsal " +
                 "INNER JOIN (SELECT no_rawat, MIN(tgl_masuk) AS tgl_masuk_pertama FROM kamar_inap GROUP BY no_rawat) km ON km.no_rawat = rp.no_rawat " +
                 "WHERE rp.status_lanjut = 'Ranap' " +
                 "AND rp.stts <> 'Batal' " +
                 "AND ki.tgl_keluar IS NOT NULL AND ki.tgl_keluar <> '0000-00-00' " +
                 "AND ki.tgl_keluar BETWEEN ? AND ? " +
                 "AND ki.stts_pulang NOT IN ('Pindah Kamar','pindah kamar','-') " +
                 "AND " + kondisiKategori(kategori) + " " +
                 "GROUP BY rp.no_rawat " +
                 ") x";
    try (PreparedStatement ps = koneksi.prepareStatement(sql)) {
        ps.setString(1, tglAwal);
        ps.setString(2, tglAkhir);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                return rs.getInt("total");
            }
        }
    }
    return 0;
}

private int getJumlahPasienKeluarHidupMati(String kategori, String tglAwal, String tglAkhir) throws SQLException {
    String sql = "SELECT COUNT(DISTINCT rp.no_rawat) AS total " +
                 "FROM reg_periksa rp " +
                 "INNER JOIN kamar_inap ki ON rp.no_rawat = ki.no_rawat " +
                 "INNER JOIN kamar k ON k.kd_kamar = ki.kd_kamar " +
                 "INNER JOIN bangsal b ON b.kd_bangsal = k.kd_bangsal " +
                 "WHERE rp.status_lanjut = 'Ranap' " +
                 "AND rp.stts <> 'Batal' " +
                 "AND ki.tgl_keluar IS NOT NULL AND ki.tgl_keluar <> '0000-00-00' " +
                 "AND ki.tgl_keluar BETWEEN ? AND ? " +
                 "AND ki.stts_pulang NOT IN ('Pindah Kamar','pindah kamar','-') " +
                 "AND " + kondisiKategori(kategori);
    try (PreparedStatement ps = koneksi.prepareStatement(sql)) {
        ps.setString(1, tglAwal);
        ps.setString(2, tglAkhir);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                return rs.getInt("total");
            }
        }
    }
    return 0;
}

private int getJumlahPasienMati(String kategori, String tglAwal, String tglAkhir) throws SQLException {
    String sql = "SELECT COUNT(DISTINCT rp.no_rawat) AS total " +
                 "FROM reg_periksa rp " +
                 "INNER JOIN kamar_inap ki ON rp.no_rawat = ki.no_rawat " +
                 "INNER JOIN kamar k ON k.kd_kamar = ki.kd_kamar " +
                 "INNER JOIN bangsal b ON b.kd_bangsal = k.kd_bangsal " +
                 "WHERE rp.status_lanjut = 'Ranap' " +
                 "AND rp.stts <> 'Batal' " +
                 "AND ki.tgl_keluar IS NOT NULL AND ki.tgl_keluar <> '0000-00-00' " +
                 "AND ki.tgl_keluar BETWEEN ? AND ? " +
                 "AND LOWER(ki.stts_pulang) LIKE '%meninggal%' " +
                 "AND " + kondisiKategori(kategori);
    try (PreparedStatement ps = koneksi.prepareStatement(sql)) {
        ps.setString(1, tglAwal);
        ps.setString(2, tglAkhir);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                return rs.getInt("total");
            }
        }
    }
    return 0;
}

private int getJumlahPasienMatiLebih48Jam(String kategori, String tglAwal, String tglAkhir) throws SQLException {
    String sql = "SELECT COUNT(DISTINCT CASE WHEN TIMESTAMPDIFF(HOUR, km.masuk_pertama, CONCAT(ki.tgl_keluar, ' ', IFNULL(NULLIF(ki.jam_keluar,''),'00:00:00'))) >= 48 THEN rp.no_rawat END) AS total " +
                 "FROM reg_periksa rp " +
                 "INNER JOIN kamar_inap ki ON rp.no_rawat = ki.no_rawat " +
                 "INNER JOIN kamar k ON k.kd_kamar = ki.kd_kamar " +
                 "INNER JOIN bangsal b ON b.kd_bangsal = k.kd_bangsal " +
                 "INNER JOIN (SELECT no_rawat, MIN(CONCAT(tgl_masuk, ' ', IFNULL(NULLIF(jam_masuk,''),'00:00:00'))) AS masuk_pertama FROM kamar_inap GROUP BY no_rawat) km ON km.no_rawat = rp.no_rawat " +
                 "WHERE rp.status_lanjut = 'Ranap' " +
                 "AND rp.stts <> 'Batal' " +
                 "AND ki.tgl_keluar IS NOT NULL AND ki.tgl_keluar <> '0000-00-00' " +
                 "AND ki.tgl_keluar BETWEEN ? AND ? " +
                 "AND LOWER(ki.stts_pulang) LIKE '%meninggal%' " +
                 "AND " + kondisiKategori(kategori);
    try (PreparedStatement ps = koneksi.prepareStatement(sql)) {
        ps.setString(1, tglAwal);
        ps.setString(2, tglAkhir);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                return rs.getInt("total");
            }
        }
    }
    return 0;
}

private int getJumlahHariDalamPeriode(String tglAwal, String tglAkhir) {
    return (int) ChronoUnit.DAYS.between(LocalDate.parse(tglAwal), LocalDate.parse(tglAkhir)) + 1;
}

private String getLabelPeriode(String tglAwal, String tglAkhir) {
    try {
        LocalDate awal = LocalDate.parse(tglAwal);
        LocalDate akhir = LocalDate.parse(tglAkhir);

        if (awal.getYear() == akhir.getYear()
                && awal.getMonthValue() == 1
                && awal.getDayOfMonth() == 1
                && akhir.getMonthValue() == 12
                && akhir.getDayOfMonth() == 31) {
            return "Tahun " + awal.getYear();
        }

        if (awal.getYear() == akhir.getYear()
                && awal.getMonthValue() == akhir.getMonthValue()
                && awal.getDayOfMonth() == 1
                && akhir.getDayOfMonth() == akhir.lengthOfMonth()) {
            return getNamaBulanIndonesia(awal.getMonthValue()) + " " + awal.getYear();
        }

        return tanggalIndonesia(awal) + " s.d. " + tanggalIndonesia(akhir);
    } catch (Exception e) {
        return Tgl1.getSelectedItem() + " s.d. " + Tgl2.getSelectedItem();
    }
}

private String tanggalIndonesia(LocalDate tanggal) {
    return String.format("%02d %s %d", tanggal.getDayOfMonth(), getNamaBulanIndonesia(tanggal.getMonthValue()), tanggal.getYear());
}

private String getNamaBulanIndonesia(int bulan) {
    String[] namaBulan = {
        "", "Januari", "Februari", "Maret", "April", "Mei", "Juni",
        "Juli", "Agustus", "September", "Oktober", "November", "Desember"
    };
    if (bulan >= 1 && bulan <= 12) {
        return namaBulan[bulan];
    }
    return "";
}

private String kondisiKategori(String kategori) {
    if (kategori.equals("SEMUA")) {
        return "1=1";
    }
    String kolom = "UPPER(CONCAT(IFNULL(k.kelas,''),' ',IFNULL(b.nm_bangsal,'')))";
    String icu = "(" + kolom + " LIKE '%ICU%' AND " + kolom + " NOT LIKE '%NICU%' AND " + kolom + " NOT LIKE '%PICU%' AND " + kolom + " NOT LIKE '%RICU%' AND " + kolom + " NOT LIKE '%ICCU%' AND " + kolom + " NOT LIKE '%ICVCU%' AND " + kolom + " NOT LIKE '%HCU%')";
    String nicu = "(" + kolom + " LIKE '%NICU%')";
    String picu = "(" + kolom + " LIKE '%PICU%')";
    String intensifLainnya = "(" + kolom + " LIKE '%HCU%' OR " + kolom + " LIKE '%ICCU%' OR " + kolom + " LIKE '%ICVCU%' OR " + kolom + " LIKE '%RICU%')";

    if (kategori.equals("ICU")) {
        return icu;
    } else if (kategori.equals("NICU")) {
        return nicu;
    } else if (kategori.equals("PICU")) {
        return picu;
    } else if (kategori.equals("INTENSIF_LAINNYA")) {
        return intensifLainnya;
    } else {
        return "NOT (" + icu + " OR " + nicu + " OR " + picu + " OR " + intensifLainnya + ")";
    }
}

private String angka(double nilai) {
    return Valid.SetAngka(nilai);
}

private String escapeHtml(String text) {
    if (text == null) {
        return "";
    }
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;").replace("'", "&#39;");
}

private static class DataIndikator {
    int tt = 0;
    int hariPerawatan = 0;
    int lamaDirawat = 0;
    int pasienKeluar = 0;
    int matiLebih48 = 0;
    int matiTotal = 0;
    double bor = 0;
    double alos = 0;
    double bto = 0;
    double toi = 0;
    double ndr = 0;
    double gdr = 0;
}


}
