/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DlgKtgPenyakit.java
 *
 * Created on May 23, 2010, 12:15:01 AM
 */

package laporan;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dosen
 */
public final class VerifikasiTB extends javax.swing.JDialog {
    
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private PreparedStatement ps;
    private ResultSet rs;
    private int i;
    private final ButtonGroup bgSiTB = new ButtonGroup();    

    /** Creates new form DlgKtgPenyakit
     * @param parent
     * @param modal */
    public VerifikasiTB(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Group radio buttons (Sudah Ada / Belum Ada)
        initButtonGroup();
        // Default selections
        R2.setSelected(true); // default "Belum Ada"
        updateSITBVisibility();
        CheckBoxYA.setSelected(false);
        // Initial placement/size (adjust as needed)
        this.setLocation(10, 5);
        this.setSize(450, 600);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TNoRwCari = new widget.TextBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        internalFrame1 = new widget.InternalFrame();
        panelGlass8 = new widget.panelisi();
        jLabel27 = new widget.Label();
        BtnSimpanTB = new widget.Button();
        jLabel28 = new widget.Label();
        BtnKeluar = new widget.Button();
        panelGlass2 = new widget.panelisi();
        jLabel22 = new widget.Label();
        jLabel23 = new widget.Label();
        CheckBoxYA = new javax.swing.JCheckBox();
        R1 = new widget.RadioButton();
        R2 = new widget.RadioButton();
        jLabel25 = new widget.Label();
        NoSITB = new widget.TextBox();
        jLabelNoSITB = new widget.Label();
        jPanel1 = new javax.swing.JPanel();
        LblIdentitas = new widget.Label();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        TindakLanjut = new widget.TextArea();
        jLabel24 = new widget.Label();

        TNoRwCari.setHighlighter(null);
        TNoRwCari.setName("TNoRwCari"); // NOI18N
        TNoRwCari.setPreferredSize(new java.awt.Dimension(120, 23));
        TNoRwCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TNoRwCariMouseClicked(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setName("jTextArea1"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Verifikasi Pasien TB");
        setModal(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(450, 600));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        internalFrame1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 245, 235)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(50, 50, 50))); // NOI18N
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setPreferredSize(new java.awt.Dimension(450, 600));
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        panelGlass8.setBackground(new java.awt.Color(204, 204, 204));
        panelGlass8.setName("panelGlass8"); // NOI18N
        panelGlass8.setPreferredSize(new java.awt.Dimension(44, 60));
        panelGlass8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 9));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N
        jLabel27.setPreferredSize(new java.awt.Dimension(15, 0));
        panelGlass8.add(jLabel27);

        BtnSimpanTB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/save-16x16.png"))); // NOI18N
        BtnSimpanTB.setMnemonic('S');
        BtnSimpanTB.setText("Simpan");
        BtnSimpanTB.setToolTipText("Alt+S");
        BtnSimpanTB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnSimpanTB.setIconTextGap(10);
        BtnSimpanTB.setName("BtnSimpanTB"); // NOI18N
        BtnSimpanTB.setPreferredSize(new java.awt.Dimension(85, 30));
        BtnSimpanTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanTBActionPerformed(evt);
            }
        });
        panelGlass8.add(BtnSimpanTB);

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel28.setName("jLabel28"); // NOI18N
        jLabel28.setPreferredSize(new java.awt.Dimension(210, 0));
        panelGlass8.add(jLabel28);

        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/exit.png"))); // NOI18N
        BtnKeluar.setMnemonic('K');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+K");
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(85, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        panelGlass8.add(BtnKeluar);

        internalFrame1.add(panelGlass8, java.awt.BorderLayout.SOUTH);

        panelGlass2.setName("panelGlass2"); // NOI18N
        panelGlass2.setPreferredSize(new java.awt.Dimension(375, 600));
        panelGlass2.setLayout(null);

        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Verifikasi Pasien TB");
        jLabel22.setFont(new java.awt.Font("Segoe UI Semibold", 0, 20)); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N
        panelGlass2.add(jLabel22);
        jLabel22.setBounds(30, 20, 210, 30);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("1.   Apakah pasien ini terindikasi TB ?");
        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N
        panelGlass2.add(jLabel23);
        jLabel23.setBounds(30, 130, 300, 23);

        CheckBoxYA.setBackground(new java.awt.Color(255, 255, 255));
        CheckBoxYA.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        CheckBoxYA.setText("YA, Terindikasi TB ");
        CheckBoxYA.setIconTextGap(10);
        CheckBoxYA.setName("CheckBoxYA"); // NOI18N
        CheckBoxYA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxYAActionPerformed(evt);
            }
        });
        panelGlass2.add(CheckBoxYA);
        CheckBoxYA.setBounds(50, 160, 160, 29);

        R1.setSelected(true);
        R1.setText("Sudah Ada");
        R1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        R1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        R1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        R1.setIconTextGap(10);
        R1.setName("R1"); // NOI18N
        R1.setPreferredSize(new java.awt.Dimension(195, 23));
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });
        panelGlass2.add(R1);
        R1.setBounds(180, 240, 110, 23);

        R2.setText("Belum Ada");
        R2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        R2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        R2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        R2.setIconTextGap(10);
        R2.setName("R2"); // NOI18N
        R2.setPreferredSize(new java.awt.Dimension(185, 23));
        R2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R2ActionPerformed(evt);
            }
        });
        panelGlass2.add(R2);
        R2.setBounds(50, 240, 110, 23);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("2.   Apakah sudah Ada di SITB ?");
        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N
        panelGlass2.add(jLabel25);
        jLabel25.setBounds(30, 210, 300, 23);

        NoSITB.setHighlighter(null);
        NoSITB.setName("NoSITB"); // NOI18N
        NoSITB.setPreferredSize(new java.awt.Dimension(120, 30));
        NoSITB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NoSITBMouseClicked(evt);
            }
        });
        panelGlass2.add(NoSITB);
        NoSITB.setBounds(150, 280, 130, 30);

        jLabelNoSITB.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelNoSITB.setText("Nomor SITB  : ");
        jLabelNoSITB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelNoSITB.setName("jLabelNoSITB"); // NOI18N
        panelGlass2.add(jLabelNoSITB);
        jLabelNoSITB.setBounds(50, 280, 100, 23);

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setName("jPanel1"); // NOI18N
        panelGlass2.add(jPanel1);
        jPanel1.setBounds(0, 0, 680, 60);

        LblIdentitas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblIdentitas.setText("123456   Mustafa Daeng Muma");
        LblIdentitas.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        LblIdentitas.setName("LblIdentitas"); // NOI18N
        panelGlass2.add(LblIdentitas);
        LblIdentitas.setBounds(30, 80, 420, 23);
        LblIdentitas.getAccessibleContext().setAccessibleName("");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setName("jSeparator1"); // NOI18N
        panelGlass2.add(jSeparator1);
        jSeparator1.setBounds(30, 110, 380, 2);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        TindakLanjut.setBackground(new java.awt.Color(255, 255, 255));
        TindakLanjut.setColumns(20);
        TindakLanjut.setForeground(new java.awt.Color(0, 0, 0));
        TindakLanjut.setRows(5);
        TindakLanjut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TindakLanjut.setName("TindakLanjut"); // NOI18N
        jScrollPane2.setViewportView(TindakLanjut);

        panelGlass2.add(jScrollPane2);
        jScrollPane2.setBounds(50, 350, 360, 140);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("3.   Keterangan :");
        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N
        panelGlass2.add(jLabel24);
        jLabel24.setBounds(30, 320, 410, 23);

        internalFrame1.add(panelGlass2, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initButtonGroup() {
    bgSiTB.add(R1); // "Sudah Ada"
    bgSiTB.add(R2); // "Belum Ada"
}
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        if (TNoRwCari.getText()!=null && !TNoRwCari.getText().trim().isEmpty()) {
            muatData();
        }
    }
                                 
    private void BtnSimpanTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanTBActionPerformed
        simpanTB();
    }//GEN-LAST:event_BtnSimpanTBActionPerformed

    private void CheckBoxYAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxYAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxYAActionPerformed

    private void TNoRwCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TNoRwCariMouseClicked
        
    }//GEN-LAST:event_TNoRwCariMouseClicked

    private void NoSITBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NoSITBMouseClicked

    }//GEN-LAST:event_NoSITBMouseClicked

    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        dispose();        
    }//GEN-LAST:event_BtnKeluarKeyPressed

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        updateSITBVisibility();
        NoSITB.requestFocus();
    }//GEN-LAST:event_R1ActionPerformed

    private void R2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R2ActionPerformed
        updateSITBVisibility();
    }//GEN-LAST:event_R2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            VerifikasiTB dialog = new VerifikasiTB(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Button BtnSimpanTB;
    private javax.swing.JCheckBox CheckBoxYA;
    private widget.Label LblIdentitas;
    private widget.TextBox NoSITB;
    private widget.RadioButton R1;
    private widget.RadioButton R2;
    private widget.TextBox TNoRwCari;
    private widget.TextArea TindakLanjut;
    private widget.InternalFrame internalFrame1;
    private widget.Label jLabel22;
    private widget.Label jLabel23;
    private widget.Label jLabel24;
    private widget.Label jLabel25;
    private widget.Label jLabel27;
    private widget.Label jLabel28;
    private widget.Label jLabelNoSITB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private widget.panelisi panelGlass2;
    private widget.panelisi panelGlass8;
    // End of variables declaration//GEN-END:variables

private void simpanTB() {
    // Ambil nilai dari UI
    String noRawat = TNoRwCari.getText().trim();
    String sitb    = null;

    if (R1.isSelected()) {
        sitb = "Sudah Ada";
    } else if (R2.isSelected()) {
        sitb = "Belum Ada";
    }

    // keterangan diisi "Terindikasi TB" kalau checkbox dicentang, jika tidak -> NULL
    String ket = CheckBoxYA.isSelected() ? "Terindikasi TB" : null;

    // NoSITB & Tindak Lanjut
    String noSITB        = (NoSITB.getText() != null) ? NoSITB.getText().trim() : "";
    String tindakLanjut  = (TindakLanjut.getText() != null) ? TindakLanjut.getText().trim() : "";

    // Validasi minimal
    if (noRawat.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No. Rawat belum diisi.");
        return;
    }
    if (sitb == null) {
        JOptionPane.showMessageDialog(this, "Pilih status SI-TB: Sudah Ada / Belum Ada.");
        return;
    }

    // Wajib isi NoSITB jika "Sudah Ada"
    if ("Sudah Ada".equals(sitb) && noSITB.isEmpty()) {
        JOptionPane.showMessageDialog(this, "No. SITB wajib diisi untuk status 'Sudah Ada'.");
        NoSITB.requestFocus();
        return;
    }

    // Validasi panjang digit NoSITB (abaikan non-digit saat menghitung)
    String noSITBDigits = noSITB.replaceAll("\\D", "");
    if (!noSITB.isEmpty() && noSITBDigits.length() > 16) {
        JOptionPane.showMessageDialog(this, "Maaf, No.SITB lebih dari 16 digit, silahkan cek kembali.");
        NoSITB.requestFocus();
        return;
    }

    // Ambil no_rkm_medis dari reg_periksa berdasarkan no_rawat
    String noRM = "";
    try (PreparedStatement psRM = koneksi.prepareStatement(
            "SELECT no_rkm_medis FROM reg_periksa WHERE no_rawat=? LIMIT 1")) {
        psRM.setString(1, noRawat);
        try (ResultSet rsRM = psRM.executeQuery()) {
            if (rsRM.next()) {
                noRM = rsRM.getString("no_rkm_medis");
            }
        }
    } catch (Exception ex) {
        System.out.println("Notifikasi ambil no_rkm_medis : " + ex.getMessage());
    }
    if (noRM == null || noRM.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "No. RM tidak ditemukan untuk No. Rawat tersebut.");
        return;
    }

    String sql = "INSERT INTO terindikasi_tb (no_rawat, sitb, keterangan, no_sitb, tindak_lanjut, no_rkm_medis) "
               + "VALUES (?, ?, ?, ?, ?, ?) "
               + "ON DUPLICATE KEY UPDATE "
               + "  sitb=VALUES(sitb), "
               + "  keterangan=VALUES(keterangan), "
               + "  no_sitb=VALUES(no_sitb), "
               + "  tindak_lanjut=VALUES(tindak_lanjut), "
               + "  no_rkm_medis=VALUES(no_rkm_medis)";

    try (PreparedStatement ps = koneksi.prepareStatement(sql)) {
        // 1 no_rawat
        ps.setString(1, noRawat);
        // 2 sitb
        ps.setString(2, sitb);
        // 3 keterangan
        if (ket == null) ps.setNull(3, java.sql.Types.VARCHAR); else ps.setString(3, ket);
        // 4 no_sitb
        if (noSITB.isEmpty()) ps.setNull(4, java.sql.Types.VARCHAR); else ps.setString(4, noSITB);
        // 5 tindak_lanjut (TEXT di DB tetap pakai setString)
        if (tindakLanjut.isEmpty()) ps.setNull(5, java.sql.Types.VARCHAR); else ps.setString(5, tindakLanjut);
        // 6 no_rkm_medis (varchar(6))
        ps.setString(6, noRM.trim());

        ps.executeUpdate();
        JOptionPane.showMessageDialog(this, "Verifikasi TB berhasil disimpan.");
        dispose(); // tutup dialog setelah sukses
    } catch (Exception e) {
        System.out.println("Notifikasi simpanTB : " + e.getMessage());
        JOptionPane.showMessageDialog(this, "Gagal menyimpan verifikasi TB.\n" + e.getMessage());
    }
}

    private static class string {

        public string() {
        }
    }
    


    /**
     * Set No. Rawat dari luar form dan langsung memuat data jika ada.
     */
    public void setNoRawat(String noRawat) {
        if (noRawat == null) noRawat = "";
        TNoRwCari.setText(noRawat.trim());
        if (!noRawat.trim().isEmpty()) {
            muatData();
            updateIdentitasPasien();

        }
    }

    /**
     * Muat data dari tabel terindikasi_tb berdasarkan no_rawat
     * dan sinkronkan ke UI.
     */
    private void muatData() {
        String noRawat = TNoRwCari.getText().trim();
        if (noRawat.isEmpty()) {
            return;
        }
        String sql = "SELECT sitb, keterangan FROM terindikasi_tb WHERE no_rawat=?";
        try (PreparedStatement ps = koneksi.prepareStatement(sql)) {
            ps.setString(1, noRawat);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    String sitb = rs.getString("sitb");
                    String ket  = rs.getString("keterangan");
                    if ("Sudah Ada".equalsIgnoreCase(sitb)) {
                        R1.setSelected(true);
                    } else {
                        R2.setSelected(true);
                    }
                    CheckBoxYA.setSelected(ket != null && !ket.trim().isEmpty());
                } else {
                    // default jika belum ada data
                    R2.setSelected(true);
                    CheckBoxYA.setSelected(false);
                }
            }
        } catch (Exception e) {
            System.out.println("Notifikasi muatData : " + e.getMessage());
        }
        updateIdentitasPasien();

    }
    
// 1) Helper: show/hide isian NoSITB
private void updateSITBVisibility() {
    boolean show = R1.isSelected();      // R1 = "Sudah Ada"
    jLabelNoSITB.setVisible(show);
    NoSITB.setVisible(show);

    // opsional (biar gak nyisa nilai lama saat disembunyikan)
    if (!show) {
        NoSITB.setText("");
    }

    // segarkan layout (aman untuk GroupLayout/AbsoluteLayout)
    jLabelNoSITB.revalidate(); jLabelNoSITB.repaint();
    NoSITB.revalidate();       NoSITB.repaint();
}

private void updateIdentitasPasien() {
    String noRawat = TNoRwCari.getText() != null ? TNoRwCari.getText().trim() : "";
    if (noRawat.isEmpty()) {
        if (LblIdentitas != null) LblIdentitas.setText("");
        return;
    }

    String sql = "SELECT p.no_rkm_medis, p.nm_pasien, rp.umurdaftar, rp.sttsumur " +
                 "FROM reg_periksa rp " +
                 "JOIN pasien p ON p.no_rkm_medis = rp.no_rkm_medis " +
                 "WHERE rp.no_rawat = ? " +
                 "LIMIT 1";

    try (PreparedStatement ps = koneksi.prepareStatement(sql)) {
        ps.setString(1, noRawat);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                String noRM   = rs.getString("no_rkm_medis");
                String nama   = rs.getString("nm_pasien");
                String umur   = rs.getString("umurdaftar");
                String stts   = rs.getString("sttsumur");

                // Rakit teks umur: tampil abu-abu
                    String umurFmt = "";
                    if (umur != null && !umur.trim().isEmpty() && stts != null && !stts.trim().isEmpty()) {
                        umurFmt = " <font color='#888888'> [ " + umur.trim() + " " + stts.trim() + " ]</font>";
                    }

                    // Versi A: seluruh baris tetap bold, umur abu-abu (bold + abu-abu)
                    String html = "<html><b>"
                            + (noRM == null ? "" : noRM) + "&nbsp;&nbsp;"
                            + (nama == null ? "" : nama)
                            + umurFmt
                            + "</b></html>";
                    LblIdentitas.setText(html);

                if (LblIdentitas != null) {
                    LblIdentitas.setText(html);
                }
            } else {
                if (LblIdentitas != null) LblIdentitas.setText("");
            }
        }
    } catch (Exception e) {
        System.out.println("Notifikasi updateIdentitasPasien : " + e.getMessage());
        if (LblIdentitas != null) LblIdentitas.setText("");
    }
}

}
