/*
  Dilarang keras menggandakan/mengcopy/menyebarkan/membajak/mendecompile 
  Software ini dalam bentuk apapun tanpa seijin pembuat software
  (Khanza.Soft Media). Bagi yang sengaja membajak softaware ini ta
  npa ijin, kami sumpahi sial 1000 turunan, miskin sampai 500 turu
  nan. Selalu mendapat kecelakaan sampai 400 turunan. Anak pertama
  nya cacat tidak punya kaki sampai 300 turunan. Susah cari jodoh
  sampai umur 50 tahun sampai 200 turunan. Ya Alloh maafkan kami 
  karena telah berdoa buruk, semua ini kami lakukan karena kami ti
  dak pernah rela karya kami dibajak tanpa ijin.
 */

package wa;

import fungsi.koneksiDB;
import fungsi.sekuel;
import fungsi.validasi;
import java.awt.event.KeyEvent;
import java.sql.Connection; 
import java.util.Date; 
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.ProtocolException;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.logging.Level;
import java.util.logging.Logger;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import fungsi.akses;
import fungsi.koneksiDBWA;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import wa.WhatsappMasterTemplate;
import wa.WhatsappTemplate;
/**
 *
 * @author perpustakaan
 */
public class WhatsappKirimFonnte extends javax.swing.JDialog {
    private Connection koneksi=koneksiDB.condb();
    private sekuel Sequel=new sekuel();
    private validasi Valid=new validasi();
    private PreparedStatement ps;
    private ResultSet rs;
    private WhatsappTemplate templateWA=new WhatsappTemplate(null,false);
    
    
    private WhatsappTemplate pasien=new WhatsappTemplate(null,false);
    
//    private WhatsappMasterTemplate whatsapptemp=new WhatsappMasterTemplate(null,false);
    private WhatsappRiwayat whastappriwayat=new WhatsappRiwayat(null,false);
    
    

    /** Creates new form DlgPemberianObat
     * @param parent
     * @param modal */
    public WhatsappKirimFonnte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setLocation(8,1);
        setSize(885,674);
        
        //TCatatan.setText(TCatatan); 
//        TPesan.setLineWrap(true);
//        TPesan.setWrapStyleWord(true); 
         
         
        
        WhatsappTemplate template = new WhatsappTemplate(null, false); 
        template.addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                TPoli.setText("Window Opened");
            }

            @Override
            public void windowClosing(WindowEvent e) {
                TPoli.setText("Window Closing");
            }

            @Override
            public void windowClosed(WindowEvent e) {
                TPoli.setText("Window Closed");
            }
        });
        
        templateWA.addWindowListener(new WindowListener() {
            @Override
            public void windowOpened(WindowEvent e) {;}
            @Override
            public void windowClosing(WindowEvent e) {}
            @Override
            public void windowClosed(WindowEvent e) {
            //    if(akses.getform().equals("WhatsappKirimFonnte")){
                    if(templateWA.getTable().getSelectedRow()!= -1){                    
                        TPesan.setText(templateWA.getTable().getValueAt(templateWA.getTable().getSelectedRow(),2).toString());

                //    }
                }
            }
            
            @Override
            public void windowIconified(WindowEvent e) {}
            @Override
            public void windowDeiconified(WindowEvent e) {}
            @Override
            public void windowActivated(WindowEvent e) {}
            @Override
            public void windowDeactivated(WindowEvent e) {}
        });
        
        
        
        
        
        
        
    }

    //private DlgCariObatPenyakit dlgobtpny=new DlgCariObatPenyakit(null,false);
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame1 = new widget.InternalFrame();
        FormInput = new widget.PanelBiasa();
        Scroll3 = new widget.ScrollPane();
        TPesan = new widget.TextArea();
        BtnTemplate = new widget.Button();
        BtnKirim = new widget.Button();
        BtnKeluar = new widget.Button();
        BtnTemplate1 = new widget.Button();
        NoHp = new javax.swing.JTextField();
        TDokter = new javax.swing.JTextField();
        TPasien = new javax.swing.JTextField();
        TNoRM = new javax.swing.JTextField();
        NoReg = new javax.swing.JTextField();
        TPoli = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        DTPReg = new widget.Tanggal();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Status = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Kirim Pesan Whatsapp");
        setMinimumSize(new java.awt.Dimension(725, 579));
        setModal(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        internalFrame1.setBackground(new java.awt.Color(255, 255, 255));
        internalFrame1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        internalFrame1.setForeground(new java.awt.Color(51, 51, 51));
        internalFrame1.setMinimumSize(new java.awt.Dimension(725, 579));
        internalFrame1.setName("internalFrame1"); // NOI18N
        internalFrame1.setPreferredSize(new java.awt.Dimension(725, 579));
        internalFrame1.setLayout(new java.awt.BorderLayout(1, 1));

        FormInput.setBackground(new java.awt.Color(255, 255, 255));
        FormInput.setForeground(new java.awt.Color(51, 51, 51));
        FormInput.setName("FormInput"); // NOI18N
        FormInput.setPreferredSize(new java.awt.Dimension(725, 602));
        FormInput.setLayout(null);

        Scroll3.setName("Scroll3"); // NOI18N
        Scroll3.setOpaque(true);

        TPesan.setColumns(20);
        TPesan.setRows(5);
        TPesan.setText("Salam,\n\n*{nama}*, No. Rekam Medis  *{rm}*, diinformasikan bahwa jadwal kontrol Bapak / Ibu ke \n\n     Poliklinik *{poli}*,\n     Dokter Spesialis *{dokter}*\n     Tgl. Kontrol *{tanggal}*\n\nUntuk datang kontrol di RS. Akademis Jaury Jusuf Putera Makassar sesuai dengan jadwal di atas. \nDimohon untuk datang lebih awal _( 1 jam Sebelum Praktek Dokter)_. \nJika Anda pasien _*BPJS Kesehatan*_ , Pendaftaran Wajib menggunakan Aplikasi _*JKN Mobile*_. \n\nTerima kasih, selamat beraktifitas dan selalu jaga kesehatan.\nInfo lebih lanjut, hubungi Customer service 085242554146");
        TPesan.setName("TPesan"); // NOI18N
        Scroll3.setViewportView(TPesan);

        FormInput.add(Scroll3);
        Scroll3.setBounds(20, 140, 670, 350);

        BtnTemplate.setForeground(new java.awt.Color(51, 51, 51));
        BtnTemplate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/comments.png"))); // NOI18N
        BtnTemplate.setMnemonic('G');
        BtnTemplate.setText("Template");
        BtnTemplate.setToolTipText("");
        BtnTemplate.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnTemplate.setName("BtnTemplate"); // NOI18N
        BtnTemplate.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTemplateActionPerformed(evt);
            }
        });
        BtnTemplate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnTemplateKeyPressed(evt);
            }
        });
        FormInput.add(BtnTemplate);
        BtnTemplate.setBounds(20, 500, 100, 30);

        BtnKirim.setForeground(new java.awt.Color(51, 51, 51));
        BtnKirim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/email.png"))); // NOI18N
        BtnKirim.setMnemonic('T');
        BtnKirim.setText("Kirim Pesan");
        BtnKirim.setToolTipText("Alt+T");
        BtnKirim.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnKirim.setIconTextGap(8);
        BtnKirim.setName("BtnKirim"); // NOI18N
        BtnKirim.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKirimActionPerformed(evt);
            }
        });
        BtnKirim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKirimKeyPressed(evt);
            }
        });
        FormInput.add(BtnKirim);
        BtnKirim.setBounds(260, 500, 120, 30);

        BtnKeluar.setBorder(null);
        BtnKeluar.setForeground(new java.awt.Color(51, 51, 51));
        BtnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/101.png"))); // NOI18N
        BtnKeluar.setMnemonic('T');
        BtnKeluar.setText("Keluar");
        BtnKeluar.setToolTipText("Alt+T");
        BtnKeluar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        BtnKeluar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnKeluar.setName("BtnKeluar"); // NOI18N
        BtnKeluar.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKeluarActionPerformed(evt);
            }
        });
        BtnKeluar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnKeluarKeyPressed(evt);
            }
        });
        FormInput.add(BtnKeluar);
        BtnKeluar.setBounds(630, 500, 60, 30);

        BtnTemplate1.setForeground(new java.awt.Color(51, 51, 51));
        BtnTemplate1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/conversation.png"))); // NOI18N
        BtnTemplate1.setMnemonic('G');
        BtnTemplate1.setText("Riwayat Chat");
        BtnTemplate1.setToolTipText("");
        BtnTemplate1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BtnTemplate1.setName("BtnTemplate1"); // NOI18N
        BtnTemplate1.setPreferredSize(new java.awt.Dimension(100, 30));
        BtnTemplate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTemplate1ActionPerformed(evt);
            }
        });
        BtnTemplate1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                BtnTemplate1KeyPressed(evt);
            }
        });
        FormInput.add(BtnTemplate1);
        BtnTemplate1.setBounds(130, 500, 120, 30);

        NoHp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NoHp.setBorder(null);
        NoHp.setName("NoHp"); // NOI18N
        FormInput.add(NoHp);
        NoHp.setBounds(120, 110, 270, 14);

        TDokter.setEditable(false);
        TDokter.setBackground(new java.awt.Color(255, 255, 255));
        TDokter.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TDokter.setBorder(null);
        TDokter.setName("TDokter"); // NOI18N
        FormInput.add(TDokter);
        TDokter.setBounds(120, 70, 490, 14);

        TPasien.setEditable(false);
        TPasien.setBackground(new java.awt.Color(255, 255, 255));
        TPasien.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TPasien.setBorder(null);
        TPasien.setName("TPasien"); // NOI18N
        FormInput.add(TPasien);
        TPasien.setBounds(120, 50, 490, 14);

        TNoRM.setEditable(false);
        TNoRM.setBackground(new java.awt.Color(255, 255, 255));
        TNoRM.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TNoRM.setBorder(null);
        TNoRM.setName("TNoRM"); // NOI18N
        FormInput.add(TNoRM);
        TNoRM.setBounds(120, 30, 470, 14);

        NoReg.setEditable(false);
        NoReg.setBackground(new java.awt.Color(255, 255, 255));
        NoReg.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        NoReg.setBorder(null);
        NoReg.setName("NoReg"); // NOI18N
        FormInput.add(NoReg);
        NoReg.setBounds(120, 10, 350, 14);

        TPoli.setEditable(false);
        TPoli.setBackground(new java.awt.Color(255, 255, 255));
        TPoli.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TPoli.setBorder(null);
        TPoli.setName("TPoli"); // NOI18N
        FormInput.add(TPoli);
        TPoli.setBounds(120, 90, 490, 14);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Poli Tujuan :  ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel1.setName("jLabel1"); // NOI18N
        FormInput.add(jLabel1);
        jLabel1.setBounds(10, 90, 110, 15);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("No. Antrian :  ");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel2.setName("jLabel2"); // NOI18N
        FormInput.add(jLabel2);
        jLabel2.setBounds(10, 10, 110, 15);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("No. RM :  ");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel4.setName("jLabel4"); // NOI18N
        FormInput.add(jLabel4);
        jLabel4.setBounds(10, 30, 110, 13);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("No. Whatsapp :  ");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel7.setName("jLabel7"); // NOI18N
        FormInput.add(jLabel7);
        jLabel7.setBounds(10, 110, 110, 15);

        DTPReg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12-12-2024" }));
        DTPReg.setDisplayFormat("dd-MM-yyyy");
        DTPReg.setName("DTPReg"); // NOI18N
        DTPReg.setOpaque(false);
        DTPReg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                DTPRegItemStateChanged(evt);
            }
        });
        DTPReg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DTPRegKeyPressed(evt);
            }
        });
        FormInput.add(DTPReg);
        DTPReg.setBounds(600, 10, 90, 23);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Nama Pasien :  ");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel6.setName("jLabel6"); // NOI18N
        FormInput.add(jLabel6);
        jLabel6.setBounds(10, 50, 110, 15);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Dokter Spesialis :  ");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel5.setName("jLabel5"); // NOI18N
        FormInput.add(jLabel5);
        jLabel5.setBounds(10, 70, 110, 15);

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Ubah Tgl. Kontrol :  ");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel8.setName("jLabel8"); // NOI18N
        FormInput.add(jLabel8);
        jLabel8.setBounds(480, 10, 120, 15);

        Status.setEditable(false);
        Status.setBackground(new java.awt.Color(255, 255, 255));
        Status.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Status.setBorder(null);
        Status.setName("Status"); // NOI18N
        FormInput.add(Status);
        Status.setBounds(480, 90, 210, 14);

        internalFrame1.add(FormInput, java.awt.BorderLayout.CENTER);
        FormInput.getAccessibleContext().setAccessibleName("");
        FormInput.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(internalFrame1, java.awt.BorderLayout.CENTER);
        internalFrame1.getAccessibleContext().setAccessibleDescription("::[ Kirim Pesan Whatsapp ]::");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void BtnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKeluarActionPerformed
        dispose();
}//GEN-LAST:event_BtnKeluarActionPerformed

    private void BtnKeluarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKeluarKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
            dispose();
        }
}//GEN-LAST:event_BtnKeluarKeyPressed

private void BtnTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTemplateActionPerformed

    try {
    //  WhatsappTemplate whatsappTemplate = new WhatsappTemplate(null, false);
        // whatsappTemplate.setNoRawat(TNoRM.getText());
        templateWA.tampil();
        templateWA.setSize(internalFrame1.getWidth() - 20, internalFrame1.getHeight() - 20);
        templateWA.setLocationRelativeTo(internalFrame1);
        templateWA.setVisible(true);
    } catch (Exception e) {
        // Handle exception (jika ada)
        e.printStackTrace(); // Gantilah ini dengan penanganan yang sesuai
    }
           
}//GEN-LAST:event_BtnTemplateActionPerformed

private void BtnTemplateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnTemplateKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_SPACE){
           
        }
}//GEN-LAST:event_BtnTemplateKeyPressed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        TPesan.requestFocus();
    }//GEN-LAST:event_formWindowActivated

    private void BtnKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKirimActionPerformed
        if(NoHp.getText().trim().equals("")||NoHp.getText().trim().equals("")){
            Valid.textKosong(NoHp,"No.Rekam Medis");
        }else if(TPesan.getText().trim().equals("")){
            Valid.textKosong(TPesan,"Isi Pesan Terlebih dahulu.. ");
        }else{  
        try {                                         
            String url = "https://api.fonnte.com/send";
            String TokenWA = koneksiDBWA.TOKENWA();
            
            
            // Parameter yang akan dikirimkan
            String target = NoHp.getText()+"|"+TPasien.getText()+"|"+TNoRM.getText()+"|"+NoReg.getText()+"|"+TPoli.getText()+"|"+TDokter.getText()+"|"+DTPReg.getSelectedItem();
            String message = TPesan.getText();
            String pesan = TPesan.getText();
            String kontrol = "Salam,\n "
                            + "*{nama}*, No. Rekam Medis  *{rm}*, diinformasikan bahwa jadwal kontrol Bapak / Ibu ke \n"
                            + "Poliklinik *{poli}* \n "
                            + "Dokter Spesialis *{dokter}* \n "
                            + "Tgl. Kontrol *{tanggal}* \n "
                            + "\n"
                            + "Untuk datang kontrol di RS. Akademis Jaury Jusuf Putera Makassar sesuai dengan jadwal di atas.\n" 
                            + "Dimohon untuk datang lebih awal _( 1 jam Sebelum Praktek Dokter)_.\n" 
                            + "Jika Anda pasien _*BPJS Kesehatan*_ , Pendaftaran Wajib menggunakan Aplikasi _*JKN Mobile*_. \n" 
                            + "\n"
                            + "Terima kasih, selamat beraktifitas dan selalu jaga kesehatan.\n"
                            + "Info lebih lanjut, hubungi Customer service 085242554146";
            
            String countryCode = "62"; // optional            
            String tanggal = (String) DTPReg.getSelectedItem();
            message = message.replace("{nama}", TPasien.getText())
                 .replace("{rm}", TNoRM.getText())
                 .replace("{antrian}", NoReg.getText())
                 .replace("{poli}", TPoli.getText())
                 .replace("{dokter}", TDokter.getText())
                 .replace("{tanggal}", tanggal); 
            
            pesan = pesan.replace("{nama}", TPasien.getText())
                 .replace("{rm}", TNoRM.getText())
                 .replace("{antrian}", NoReg.getText())
                 .replace("{poli}", TPoli.getText())
                 .replace("{dokter}", TDokter.getText())
                 .replace("{tanggal}", tanggal)
                 .replace("*", "")
                 .replace("_", "")
                 .replace("{", "")
                 .replace("}", "");
                 
               
            
             
            // Menggabungkan parameter ke dalam format yang sesuai untuk dikirimkan
            String postData = "target=" + target + "&message=" + message + "&countryCode=" + countryCode + "&kontrol=" + kontrol;
            
            // Membuat objek URL
            URL obj = new URL(url);
            
            // Membuka koneksi HttpURLConnection
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();
            
            // Mengatur properti untuk koneksi
            con.setRequestMethod("POST");
            con.setRequestProperty("Authorization", TokenWA);
            con.setDoOutput(true);
            
            // Mengirim data
            try (DataOutputStream wr = new DataOutputStream(con.getOutputStream())) {
                wr.write(postData.getBytes(StandardCharsets.UTF_8));
            } catch (IOException ex) {
                Logger.getLogger(WhatsappKirimFonnte.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            // Menerima respon dari server
            try (BufferedReader in = new BufferedReader(new InputStreamReader(con.getInputStream()))) {
                String inputLine;
                StringBuilder response = new StringBuilder();
                
                while ((inputLine = in.readLine()) != null) {
                    response.append(inputLine);
                }
                
                // Menampilkan respon
                System.out.println(response.toString());
        
        ObjectMapper objectMapper = new ObjectMapper();
        // Mengonversi JSON String menjadi JsonNode
        JsonNode jsonNode = objectMapper.readTree(response.toString());
        
        // Menampilkan nilai JSON
//        System.out.println("detail: " + jsonNode.get("detail").asText());
//        System.out.println("id: " + jsonNode.get("id").get(0).asText());
//        System.out.println("proses: " + jsonNode.get("process").asText());
//        System.out.println("status: " + jsonNode.get("status").asText());
//        System.out.println("target: " + jsonNode.get("target").get(0).asText());
        

    if ("false".equals(jsonNode.get("status").asText())) {
        //pesan error     
        JOptionPane.showMessageDialog(null, "Gagal mengirim, mohon cek koneksi Whatsapp Gateway !!", "Error", JOptionPane.ERROR_MESSAGE);
            
        } else if ("true".equals(jsonNode.get("status").asText())) {
         LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

        // Mengonversi LocalDateTime ke String dengan format yang diinginkan
        String DateNow = now.format(formatter);
        Sequel.queryu("insert into wa_report values('"+jsonNode.get("id").get(0).asText()+"','"+TNoRM.getText()+"','"+NoHp.getText()+"','"+akses.getkode()+"','SIMRS Khanza','"+jsonNode.get("target").get(0).asText()+"','"+kontrol+"','','"+jsonNode.get("status").asText()+"','','"+DateNow+"','"+DateNow+"')");
        //pesan sukses     
        JOptionPane.showMessageDialog(null, "Berhasil Mengirim Pesan !!", "Success", JOptionPane.INFORMATION_MESSAGE);
        BtnKeluarActionPerformed(evt);
        }

       
            } catch (IOException ex) {
                Logger.getLogger(WhatsappKirimFonnte.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } catch (ProtocolException ex) {
            Logger.getLogger(WhatsappKirimFonnte.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(WhatsappKirimFonnte.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
    }          
    }//GEN-LAST:event_BtnKirimActionPerformed

    private void BtnKirimKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnKirimKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnKirimKeyPressed

    private void BtnTemplate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTemplate1ActionPerformed
        // TODO add your handling code here:
                                                    
whastappriwayat.setNoRawat(TNoRM.getText());
whastappriwayat.tampil();
whastappriwayat.setSize(internalFrame1.getWidth()-20,internalFrame1.getHeight()-20);
whastappriwayat.setLocationRelativeTo(internalFrame1);
whastappriwayat.setVisible(true);
    }//GEN-LAST:event_BtnTemplate1ActionPerformed

    private void BtnTemplate1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BtnTemplate1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTemplate1KeyPressed

    private void DTPRegItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_DTPRegItemStateChanged
        
    }//GEN-LAST:event_DTPRegItemStateChanged

    private void DTPRegKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DTPRegKeyPressed
         
    }//GEN-LAST:event_DTPRegKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            WhatsappKirimFonnte dialog = new WhatsappKirimFonnte(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                     System.out.println("Jendela ditutup");
                }
            });
            dialog.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private widget.Button BtnKeluar;
    private widget.Button BtnKirim;
    private widget.Button BtnTemplate;
    private widget.Button BtnTemplate1;
    private widget.Tanggal DTPReg;
    private widget.PanelBiasa FormInput;
    private javax.swing.JTextField NoHp;
    private javax.swing.JTextField NoReg;
    private widget.ScrollPane Scroll3;
    private javax.swing.JTextField Status;
    private javax.swing.JTextField TDokter;
    private javax.swing.JTextField TNoRM;
    private javax.swing.JTextField TPasien;
    private widget.TextArea TPesan;
    private javax.swing.JTextField TPoli;
    private widget.InternalFrame internalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
    

    private void isPsien() {
//        Sequel.cariIsi("select pasien.nm_pasien from pasien where pasien.no_rkm_medis=? ",TPasien,TNoRM.getText());
//        Sequel.cariIsi("select pasien.no_tlp from pasien where pasien.no_rkm_medis=? ",NoHp,TNoRM.getText());
    
     }

    public void setNoRm(String norm, String noreg, String poli, String dokter, Date tanggal) {
         TNoRM.setText(norm);   
         NoReg.setText(noreg); 
         TPoli.setText(poli);
         TDokter.setText(dokter);
         DTPReg.setDate(tanggal); 
        Sequel.cariIsi("select pasien.nm_pasien from pasien where pasien.no_rkm_medis=? ",TPasien,TNoRM.getText());
        Sequel.cariIsi("select pasien.no_tlp from pasien where pasien.no_rkm_medis=? ",NoHp,TNoRM.getText());
        Sequel.cariIsi("select piutang_pasien.status from piutang_pasien where piutang_pasien.no_rawat=? ",Status,TNoRM.getText());
        isPsien();   
//        Sequel.cariIsi("select catatan_pasien.catatan from catatan_pasien where catatan_pasien.no_rkm_medis=?",TCatatan,TNoRM.getText());       
    }
    
    
    public void setPesan(String dataTemplate) {
         TPesan.setText(dataTemplate); 
        isPsien();   
//        Sequel.cariIsi("select catatan_pasien.catatan from catatan_pasien where catatan_pasien.no_rkm_medis=?",TCatatan,TNoRM.getText());       
    }
    
 
    
    public void isCek(){
        BtnKirim.setEnabled(true);
        BtnTemplate.setEnabled(true);
        BtnTemplate.setEnabled(true);
       
        
    }
    
    
 
     



}
